
/* Automatically generated struct definitions for the Data API.
 * Do not edit manually, changes will be overwritten.           */

#define RNA_RUNTIME

#include <float.h>
#include <stdio.h>
#include <limits.h>
#include <string.h>

#include <stddef.h>

#include "MEM_guardedalloc.h"

#include "DNA_ID.h"
#include "DNA_scene_types.h"
#include "BLI_blenlib.h"

#include "BLI_utildefines.h"

#include "BKE_context.h"
#include "BKE_library.h"
#include "BKE_main.h"
#include "BKE_report.h"
#include "RNA_define.h"
#include "RNA_types.h"
#include "rna_internal.h"

#include "rna_prototypes_gen.h"

#include "rna_controller.c"
#include "rna_controller_api.c"

/* Autogenerated Functions */


CollectionPropertyRNA rna_Controller_rna_properties;
PointerPropertyRNA rna_Controller_rna_type;
StringPropertyRNA rna_Controller_name;
EnumPropertyRNA rna_Controller_type;
BoolPropertyRNA rna_Controller_show_expanded;
BoolPropertyRNA rna_Controller_active;
BoolPropertyRNA rna_Controller_use_priority;
CollectionPropertyRNA rna_Controller_actuators;
IntPropertyRNA rna_Controller_states;

extern FunctionRNA rna_Controller_link_func;
extern PointerPropertyRNA rna_Controller_link_sensor;
extern PointerPropertyRNA rna_Controller_link_actuator;

extern FunctionRNA rna_Controller_unlink_func;
extern PointerPropertyRNA rna_Controller_unlink_sensor;
extern PointerPropertyRNA rna_Controller_unlink_actuator;



extern CollectionPropertyRNA rna_Controller_rna_properties;
extern PointerPropertyRNA rna_Controller_rna_type;
extern StringPropertyRNA rna_Controller_name;
extern EnumPropertyRNA rna_Controller_type;
extern BoolPropertyRNA rna_Controller_show_expanded;
extern BoolPropertyRNA rna_Controller_active;
extern BoolPropertyRNA rna_Controller_use_priority;
extern CollectionPropertyRNA rna_Controller_actuators;
extern IntPropertyRNA rna_Controller_states;

StringPropertyRNA rna_ExpressionController_expression;

extern FunctionRNA rna_Controller_link_func;
extern PointerPropertyRNA rna_Controller_link_sensor;
extern PointerPropertyRNA rna_Controller_link_actuator;

extern FunctionRNA rna_Controller_unlink_func;
extern PointerPropertyRNA rna_Controller_unlink_sensor;
extern PointerPropertyRNA rna_Controller_unlink_actuator;



extern CollectionPropertyRNA rna_Controller_rna_properties;
extern PointerPropertyRNA rna_Controller_rna_type;
extern StringPropertyRNA rna_Controller_name;
extern EnumPropertyRNA rna_Controller_type;
extern BoolPropertyRNA rna_Controller_show_expanded;
extern BoolPropertyRNA rna_Controller_active;
extern BoolPropertyRNA rna_Controller_use_priority;
extern CollectionPropertyRNA rna_Controller_actuators;
extern IntPropertyRNA rna_Controller_states;

EnumPropertyRNA rna_PythonController_mode;
PointerPropertyRNA rna_PythonController_text;
StringPropertyRNA rna_PythonController_module;
BoolPropertyRNA rna_PythonController_use_debug;

extern FunctionRNA rna_Controller_link_func;
extern PointerPropertyRNA rna_Controller_link_sensor;
extern PointerPropertyRNA rna_Controller_link_actuator;

extern FunctionRNA rna_Controller_unlink_func;
extern PointerPropertyRNA rna_Controller_unlink_sensor;
extern PointerPropertyRNA rna_Controller_unlink_actuator;



extern CollectionPropertyRNA rna_Controller_rna_properties;
extern PointerPropertyRNA rna_Controller_rna_type;
extern StringPropertyRNA rna_Controller_name;
extern EnumPropertyRNA rna_Controller_type;
extern BoolPropertyRNA rna_Controller_show_expanded;
extern BoolPropertyRNA rna_Controller_active;
extern BoolPropertyRNA rna_Controller_use_priority;
extern CollectionPropertyRNA rna_Controller_actuators;
extern IntPropertyRNA rna_Controller_states;

extern FunctionRNA rna_Controller_link_func;
extern PointerPropertyRNA rna_Controller_link_sensor;
extern PointerPropertyRNA rna_Controller_link_actuator;

extern FunctionRNA rna_Controller_unlink_func;
extern PointerPropertyRNA rna_Controller_unlink_sensor;
extern PointerPropertyRNA rna_Controller_unlink_actuator;



extern CollectionPropertyRNA rna_Controller_rna_properties;
extern PointerPropertyRNA rna_Controller_rna_type;
extern StringPropertyRNA rna_Controller_name;
extern EnumPropertyRNA rna_Controller_type;
extern BoolPropertyRNA rna_Controller_show_expanded;
extern BoolPropertyRNA rna_Controller_active;
extern BoolPropertyRNA rna_Controller_use_priority;
extern CollectionPropertyRNA rna_Controller_actuators;
extern IntPropertyRNA rna_Controller_states;

extern FunctionRNA rna_Controller_link_func;
extern PointerPropertyRNA rna_Controller_link_sensor;
extern PointerPropertyRNA rna_Controller_link_actuator;

extern FunctionRNA rna_Controller_unlink_func;
extern PointerPropertyRNA rna_Controller_unlink_sensor;
extern PointerPropertyRNA rna_Controller_unlink_actuator;



extern CollectionPropertyRNA rna_Controller_rna_properties;
extern PointerPropertyRNA rna_Controller_rna_type;
extern StringPropertyRNA rna_Controller_name;
extern EnumPropertyRNA rna_Controller_type;
extern BoolPropertyRNA rna_Controller_show_expanded;
extern BoolPropertyRNA rna_Controller_active;
extern BoolPropertyRNA rna_Controller_use_priority;
extern CollectionPropertyRNA rna_Controller_actuators;
extern IntPropertyRNA rna_Controller_states;

extern FunctionRNA rna_Controller_link_func;
extern PointerPropertyRNA rna_Controller_link_sensor;
extern PointerPropertyRNA rna_Controller_link_actuator;

extern FunctionRNA rna_Controller_unlink_func;
extern PointerPropertyRNA rna_Controller_unlink_sensor;
extern PointerPropertyRNA rna_Controller_unlink_actuator;



extern CollectionPropertyRNA rna_Controller_rna_properties;
extern PointerPropertyRNA rna_Controller_rna_type;
extern StringPropertyRNA rna_Controller_name;
extern EnumPropertyRNA rna_Controller_type;
extern BoolPropertyRNA rna_Controller_show_expanded;
extern BoolPropertyRNA rna_Controller_active;
extern BoolPropertyRNA rna_Controller_use_priority;
extern CollectionPropertyRNA rna_Controller_actuators;
extern IntPropertyRNA rna_Controller_states;

extern FunctionRNA rna_Controller_link_func;
extern PointerPropertyRNA rna_Controller_link_sensor;
extern PointerPropertyRNA rna_Controller_link_actuator;

extern FunctionRNA rna_Controller_unlink_func;
extern PointerPropertyRNA rna_Controller_unlink_sensor;
extern PointerPropertyRNA rna_Controller_unlink_actuator;



extern CollectionPropertyRNA rna_Controller_rna_properties;
extern PointerPropertyRNA rna_Controller_rna_type;
extern StringPropertyRNA rna_Controller_name;
extern EnumPropertyRNA rna_Controller_type;
extern BoolPropertyRNA rna_Controller_show_expanded;
extern BoolPropertyRNA rna_Controller_active;
extern BoolPropertyRNA rna_Controller_use_priority;
extern CollectionPropertyRNA rna_Controller_actuators;
extern IntPropertyRNA rna_Controller_states;

extern FunctionRNA rna_Controller_link_func;
extern PointerPropertyRNA rna_Controller_link_sensor;
extern PointerPropertyRNA rna_Controller_link_actuator;

extern FunctionRNA rna_Controller_unlink_func;
extern PointerPropertyRNA rna_Controller_unlink_sensor;
extern PointerPropertyRNA rna_Controller_unlink_actuator;



extern CollectionPropertyRNA rna_Controller_rna_properties;
extern PointerPropertyRNA rna_Controller_rna_type;
extern StringPropertyRNA rna_Controller_name;
extern EnumPropertyRNA rna_Controller_type;
extern BoolPropertyRNA rna_Controller_show_expanded;
extern BoolPropertyRNA rna_Controller_active;
extern BoolPropertyRNA rna_Controller_use_priority;
extern CollectionPropertyRNA rna_Controller_actuators;
extern IntPropertyRNA rna_Controller_states;

extern FunctionRNA rna_Controller_link_func;
extern PointerPropertyRNA rna_Controller_link_sensor;
extern PointerPropertyRNA rna_Controller_link_actuator;

extern FunctionRNA rna_Controller_unlink_func;
extern PointerPropertyRNA rna_Controller_unlink_sensor;
extern PointerPropertyRNA rna_Controller_unlink_actuator;


static PointerRNA Controller_rna_properties_get(CollectionPropertyIterator *iter)
{
	return rna_builtin_properties_get(iter);
}

void Controller_rna_properties_begin(CollectionPropertyIterator *iter, PointerRNA *ptr)
{

	memset(iter, 0, sizeof(*iter));
	iter->parent = *ptr;
	iter->prop = (PropertyRNA *)&rna_Controller_rna_properties;

	rna_builtin_properties_begin(iter, ptr);

	if (iter->valid)
		iter->ptr = Controller_rna_properties_get(iter);
}

void Controller_rna_properties_next(CollectionPropertyIterator *iter)
{
	rna_builtin_properties_next(iter);

	if (iter->valid)
		iter->ptr = Controller_rna_properties_get(iter);
}

void Controller_rna_properties_end(CollectionPropertyIterator *iter)
{
	rna_iterator_listbase_end(iter);
}

int Controller_rna_properties_lookup_string(PointerRNA *ptr, const char *key, PointerRNA *r_ptr)
{
	return rna_builtin_properties_lookup_string(ptr, key, r_ptr);
}

PointerRNA Controller_rna_type_get(PointerRNA *ptr)
{
	return rna_builtin_type_get(ptr);
}

void Controller_name_get(PointerRNA *ptr, char *value)
{
	bController *data = (bController *)(ptr->data);
	BLI_strncpy_utf8(value, data->name, 64);
}

int Controller_name_length(PointerRNA *ptr)
{
	bController *data = (bController *)(ptr->data);
	return strlen(data->name);
}

void Controller_name_set(PointerRNA *ptr, const char *value)
{
	rna_Constroller_name_set(ptr, value);
}

int Controller_type_get(PointerRNA *ptr)
{
	bController *data = (bController *)(ptr->data);
	return (int)(data->type);
}

void Controller_type_set(PointerRNA *ptr, int value)
{
	rna_Controller_type_set(ptr, value);
}

int Controller_show_expanded_get(PointerRNA *ptr)
{
	bController *data = (bController *)(ptr->data);
	return (((data->flag) & 1) != 0);
}

void Controller_show_expanded_set(PointerRNA *ptr, int value)
{
	bController *data = (bController *)(ptr->data);
	if (value) data->flag |= 1;
	else data->flag &= ~1;
}

int Controller_active_get(PointerRNA *ptr)
{
	bController *data = (bController *)(ptr->data);
	return !(((data->flag) & 32) != 0);
}

void Controller_active_set(PointerRNA *ptr, int value)
{
	bController *data = (bController *)(ptr->data);
	if (!value) data->flag |= 32;
	else data->flag &= ~32;
}

int Controller_use_priority_get(PointerRNA *ptr)
{
	bController *data = (bController *)(ptr->data);
	return (((data->flag) & 16) != 0);
}

void Controller_use_priority_set(PointerRNA *ptr, int value)
{
	bController *data = (bController *)(ptr->data);
	if (value) data->flag |= 16;
	else data->flag &= ~16;
}

static PointerRNA Controller_actuators_get(CollectionPropertyIterator *iter)
{
	return rna_pointer_inherit_refine(&iter->parent, &RNA_Actuator, rna_iterator_array_dereference_get(iter));
}

void Controller_actuators_begin(CollectionPropertyIterator *iter, PointerRNA *ptr)
{

	memset(iter, 0, sizeof(*iter));
	iter->parent = *ptr;
	iter->prop = (PropertyRNA *)&rna_Controller_actuators;

	rna_Controller_actuators_begin(iter, ptr);

	if (iter->valid)
		iter->ptr = Controller_actuators_get(iter);
}

void Controller_actuators_next(CollectionPropertyIterator *iter)
{
	rna_iterator_array_next(iter);

	if (iter->valid)
		iter->ptr = Controller_actuators_get(iter);
}

void Controller_actuators_end(CollectionPropertyIterator *iter)
{
	rna_iterator_array_end(iter);
}

int Controller_actuators_lookup_int(PointerRNA *ptr, int index, PointerRNA *r_ptr)
{
	int found = 0;
	CollectionPropertyIterator iter;

	Controller_actuators_begin(&iter, ptr);

	if (iter.valid) {
		ArrayIterator *internal = &iter.internal.array;
		if (index < 0 || index >= internal->length) {
#ifdef __GNUC__
			printf("Array iterator out of range: %s (index %d)\n", __func__, index);
#else
			printf("Array iterator out of range: (index %d)\n", index);
#endif
		}
		else if (internal->skip) {
			while (index-- > 0 && iter.valid) {
				rna_iterator_array_next(&iter);
			}
			found = (index == -1 && iter.valid);
		}
		else {
			internal->ptr += internal->itemsize * index;
			found = 1;
		}
		if (found) *r_ptr = Controller_actuators_get(&iter);
	}

	Controller_actuators_end(&iter);

	return found;
}

int Controller_actuators_lookup_string(PointerRNA *ptr, const char *key, PointerRNA *r_ptr)
{
	extern int Actuator_name_length(PointerRNA *);
	extern void Actuator_name_get(PointerRNA *, char *);

	bool found = false;
	CollectionPropertyIterator iter;
	char namebuf[1024];
	char *name;

	Controller_actuators_begin(&iter, ptr);

	while (iter.valid) {
		if (iter.ptr.data) {
			int namelen = Actuator_name_length(&iter.ptr);
			if (namelen < 1024) {
				Actuator_name_get(&iter.ptr, namebuf);
				if (strcmp(namebuf, key) == 0) {
					found = true;
					*r_ptr = iter.ptr;
					break;
				}
			}
			else {
				name = MEM_mallocN(namelen+1, "name string");
				Actuator_name_get(&iter.ptr, name);
				if (strcmp(name, key) == 0) {
					MEM_freeN(name);

					found = true;
					*r_ptr = iter.ptr;
					break;
				}
				else {
					MEM_freeN(name);
				}
			}
		}
		Controller_actuators_next(&iter);
	}
	Controller_actuators_end(&iter);

	return found;
}

int Controller_states_get(PointerRNA *ptr)
{
	return rna_Controller_state_number_get(ptr);
}

void Controller_states_set(PointerRNA *ptr, int value)
{
	rna_Controller_state_number_set(ptr, value);
}

void ExpressionController_expression_get(PointerRNA *ptr, char *value)
{
	bExpressionCont *data = (bExpressionCont *)(((bController *)ptr->data)->data);
	BLI_strncpy_utf8(value, data->str, 128);
}

int ExpressionController_expression_length(PointerRNA *ptr)
{
	bExpressionCont *data = (bExpressionCont *)(((bController *)ptr->data)->data);
	return strlen(data->str);
}

void ExpressionController_expression_set(PointerRNA *ptr, const char *value)
{
	bExpressionCont *data = (bExpressionCont *)(((bController *)ptr->data)->data);
	BLI_strncpy_utf8(data->str, value, 128);
}

int PythonController_mode_get(PointerRNA *ptr)
{
	bPythonCont *data = (bPythonCont *)(((bController *)ptr->data)->data);
	return (int)(data->mode);
}

void PythonController_mode_set(PointerRNA *ptr, int value)
{
	rna_Controller_mode_set(ptr, value);
}

PointerRNA PythonController_text_get(PointerRNA *ptr)
{
	bPythonCont *data = (bPythonCont *)(((bController *)ptr->data)->data);
	return rna_pointer_inherit_refine(ptr, &RNA_Text, data->text);
}

void PythonController_text_set(PointerRNA *ptr, PointerRNA value)
{
	bPythonCont *data = (bPythonCont *)(((bController *)ptr->data)->data);
	if (value.data)
		id_lib_extern((ID *)value.data);

	data->text = value.data;
}

void PythonController_module_get(PointerRNA *ptr, char *value)
{
	bPythonCont *data = (bPythonCont *)(((bController *)ptr->data)->data);
	BLI_strncpy_utf8(value, data->module, 64);
}

int PythonController_module_length(PointerRNA *ptr)
{
	bPythonCont *data = (bPythonCont *)(((bController *)ptr->data)->data);
	return strlen(data->module);
}

void PythonController_module_set(PointerRNA *ptr, const char *value)
{
	bPythonCont *data = (bPythonCont *)(((bController *)ptr->data)->data);
	BLI_strncpy_utf8(data->module, value, 64);
}

int PythonController_use_debug_get(PointerRNA *ptr)
{
	bPythonCont *data = (bPythonCont *)(((bController *)ptr->data)->data);
	return (((data->flag) & 1) != 0);
}

void PythonController_use_debug_set(PointerRNA *ptr, int value)
{
	bPythonCont *data = (bPythonCont *)(((bController *)ptr->data)->data);
	if (value) data->flag |= 1;
	else data->flag &= ~1;
}

void Controller_link(struct bController *_self, struct bSensor *sensor, struct bActuator *actuator)
{
	rna_Controller_link(_self, sensor, actuator);
}

void Controller_link_call(bContext *C, ReportList *reports, PointerRNA *_ptr, ParameterList *_parms)
{
	struct bController *_self;
	struct bSensor *sensor;
	struct bActuator *actuator;
	char *_data;
	
	_self = (struct bController *)_ptr->data;
	_data = (char *)_parms->data;
	sensor = *((struct bSensor **)_data);
	_data += 8;
	actuator = *((struct bActuator **)_data);
	
	rna_Controller_link(_self, sensor, actuator);
}

void Controller_unlink(struct bController *_self, struct bSensor *sensor, struct bActuator *actuator)
{
	rna_Controller_unlink(_self, sensor, actuator);
}

void Controller_unlink_call(bContext *C, ReportList *reports, PointerRNA *_ptr, ParameterList *_parms)
{
	struct bController *_self;
	struct bSensor *sensor;
	struct bActuator *actuator;
	char *_data;
	
	_self = (struct bController *)_ptr->data;
	_data = (char *)_parms->data;
	sensor = *((struct bSensor **)_data);
	_data += 8;
	actuator = *((struct bActuator **)_data);
	
	rna_Controller_unlink(_self, sensor, actuator);
}

/* Repeated prototypes to detect errors */

void rna_Controller_link(struct bController *_self, struct bSensor *sensor, struct bActuator *actuator);
void rna_Controller_unlink(struct bController *_self, struct bSensor *sensor, struct bActuator *actuator);









/* Controller */
CollectionPropertyRNA rna_Controller_rna_properties = {
	{(PropertyRNA *)&rna_Controller_rna_type, NULL,
	-1, "rna_properties", 128, "Properties",
	"RNA property collection",
	0, "*",
	PROP_COLLECTION, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	Controller_rna_properties_begin, Controller_rna_properties_next, Controller_rna_properties_end, Controller_rna_properties_get, NULL, NULL, Controller_rna_properties_lookup_string, NULL, &RNA_Property
};

PointerPropertyRNA rna_Controller_rna_type = {
	{(PropertyRNA *)&rna_Controller_name, (PropertyRNA *)&rna_Controller_rna_properties,
	-1, "rna_type", 8912896, "RNA",
	"RNA type definition",
	0, "*",
	PROP_POINTER, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	Controller_rna_type_get, NULL, NULL, NULL,&RNA_Struct
};

StringPropertyRNA rna_Controller_name = {
	{(PropertyRNA *)&rna_Controller_type, (PropertyRNA *)&rna_Controller_rna_type,
	-1, "name", 262145, "Name",
	"",
	0, "*",
	PROP_STRING, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {64, 0, 0}, 0,
	NULL, 318767104, NULL, NULL,
	0, -1, NULL},
	Controller_name_get, Controller_name_length, Controller_name_set, NULL, NULL, NULL, 64, ""
};

static EnumPropertyItem rna_Controller_type_items[9] = {
	{0, "LOGIC_AND", 0, "And", "Logic And"},
	{1, "LOGIC_OR", 0, "Or", "Logic Or"},
	{4, "LOGIC_NAND", 0, "Nand", "Logic Nand"},
	{5, "LOGIC_NOR", 0, "Nor", "Logic Nor"},
	{6, "LOGIC_XOR", 0, "Xor", "Logic Xor"},
	{7, "LOGIC_XNOR", 0, "Xnor", "Logic Xnor"},
	{2, "EXPRESSION", 0, "Expression", ""},
	{3, "PYTHON", 0, "Python", ""},
	{0, NULL, 0, NULL, NULL}
};

EnumPropertyRNA rna_Controller_type = {
	{(PropertyRNA *)&rna_Controller_show_expanded, (PropertyRNA *)&rna_Controller_name,
	-1, "type", 1, "Type",
	"",
	0, "*",
	PROP_ENUM, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 318767104, NULL, NULL,
	0, -1, NULL},
	Controller_type_get, Controller_type_set, NULL, NULL, NULL, NULL, rna_Controller_type_items, 8, 0
};

BoolPropertyRNA rna_Controller_show_expanded = {
	{(PropertyRNA *)&rna_Controller_active, (PropertyRNA *)&rna_Controller_type,
	-1, "show_expanded", 4099, "Expanded",
	"Set controller expanded in the user interface",
	4, "*",
	PROP_BOOLEAN, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 318767104, NULL, NULL,
	0, -1, NULL},
	Controller_show_expanded_get, Controller_show_expanded_set, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL
};

BoolPropertyRNA rna_Controller_active = {
	{(PropertyRNA *)&rna_Controller_use_priority, (PropertyRNA *)&rna_Controller_show_expanded,
	-1, "active", 3, "Active",
	"Set the active state of the controller",
	0, "*",
	PROP_BOOLEAN, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 318767104, NULL, NULL,
	0, -1, NULL},
	Controller_active_get, Controller_active_set, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL
};

BoolPropertyRNA rna_Controller_use_priority = {
	{(PropertyRNA *)&rna_Controller_actuators, (PropertyRNA *)&rna_Controller_active,
	-1, "use_priority", 4099, "Priority",
	"Mark controller for execution before all non-marked controllers (good for startup scripts)",
	686, "*",
	PROP_BOOLEAN, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 318767104, NULL, NULL,
	0, -1, NULL},
	Controller_use_priority_get, Controller_use_priority_set, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL
};

CollectionPropertyRNA rna_Controller_actuators = {
	{(PropertyRNA *)&rna_Controller_states, (PropertyRNA *)&rna_Controller_use_priority,
	-1, "actuators", 0, "Actuators",
	"The list containing the actuators connected to the controller",
	0, "*",
	PROP_COLLECTION, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	Controller_actuators_begin, Controller_actuators_next, Controller_actuators_end, Controller_actuators_get, rna_Controller_actuators_length, Controller_actuators_lookup_int, Controller_actuators_lookup_string, NULL, &RNA_Actuator
};

IntPropertyRNA rna_Controller_states = {
	{NULL, (PropertyRNA *)&rna_Controller_actuators,
	-1, "states", 3, "",
	"Set Controller state index (1 to 30)",
	0, "*",
	PROP_INT, PROP_UNSIGNED | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 318767104, NULL, NULL,
	0, -1, NULL},
	Controller_states_get, Controller_states_set, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
	1, 30, 1, 30, 1, 0, NULL
};

PointerPropertyRNA rna_Controller_link_sensor = {
	{(PropertyRNA *)&rna_Controller_link_actuator, NULL,
	-1, "sensor", 8388608, "",
	"Sensor to link the controller to",
	0, "*",
	PROP_POINTER, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 318767104, NULL, NULL,
	0, -1, NULL},
	NULL, NULL, NULL, NULL,&RNA_Sensor
};

PointerPropertyRNA rna_Controller_link_actuator = {
	{NULL, (PropertyRNA *)&rna_Controller_link_sensor,
	-1, "actuator", 8388608, "",
	"Actuator to link the controller to",
	0, "*",
	PROP_POINTER, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 318767104, NULL, NULL,
	0, -1, NULL},
	NULL, NULL, NULL, NULL,&RNA_Actuator
};

FunctionRNA rna_Controller_link_func = {
	{(FunctionRNA *)&rna_Controller_unlink_func, NULL,
	NULL,
	{(PropertyRNA *)&rna_Controller_link_sensor, (PropertyRNA *)&rna_Controller_link_actuator}},
	"link", 0, "Link the controller with a sensor/actuator",
	Controller_link_call,
	NULL
};

PointerPropertyRNA rna_Controller_unlink_sensor = {
	{(PropertyRNA *)&rna_Controller_unlink_actuator, NULL,
	-1, "sensor", 8388608, "",
	"Sensor to unlink the controller from",
	0, "*",
	PROP_POINTER, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 318767104, NULL, NULL,
	0, -1, NULL},
	NULL, NULL, NULL, NULL,&RNA_Sensor
};

PointerPropertyRNA rna_Controller_unlink_actuator = {
	{NULL, (PropertyRNA *)&rna_Controller_unlink_sensor,
	-1, "actuator", 8388608, "",
	"Actuator to unlink the controller from",
	0, "*",
	PROP_POINTER, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 318767104, NULL, NULL,
	0, -1, NULL},
	NULL, NULL, NULL, NULL,&RNA_Actuator
};

FunctionRNA rna_Controller_unlink_func = {
	{NULL, (FunctionRNA *)&rna_Controller_link_func,
	NULL,
	{(PropertyRNA *)&rna_Controller_unlink_sensor, (PropertyRNA *)&rna_Controller_unlink_actuator}},
	"unlink", 0, "Unlink the controller from a sensor/actuator",
	Controller_unlink_call,
	NULL
};

StructRNA RNA_Controller = {
	{(ContainerRNA *)&RNA_ExpressionController, (ContainerRNA *)&RNA_Context,
	NULL,
	{(PropertyRNA *)&rna_Controller_rna_properties, (PropertyRNA *)&rna_Controller_states}},
	"Controller", NULL, NULL, 4, "Controller",
	"Game engine logic brick to process events, connecting sensors to actuators",
	"*", 17,
	(PropertyRNA *)&rna_Controller_name, (PropertyRNA *)&rna_Controller_rna_properties,
	NULL,
	NULL,
	rna_Controller_refine,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	{(FunctionRNA *)&rna_Controller_link_func, (FunctionRNA *)&rna_Controller_unlink_func}
};

/* Expression Controller */
StringPropertyRNA rna_ExpressionController_expression = {
	{NULL, NULL,
	-1, "expression", 262145, "Expression",
	"",
	0, "*",
	PROP_STRING, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {128, 0, 0}, 0,
	NULL, 318767104, NULL, NULL,
	0, -1, NULL},
	ExpressionController_expression_get, ExpressionController_expression_length, ExpressionController_expression_set, NULL, NULL, NULL, 128, ""
};

StructRNA RNA_ExpressionController = {
	{(ContainerRNA *)&RNA_PythonController, (ContainerRNA *)&RNA_Controller,
	NULL,
	{(PropertyRNA *)&rna_ExpressionController_expression, (PropertyRNA *)&rna_ExpressionController_expression}},
	"ExpressionController", NULL, NULL, 4, "Expression Controller",
	"Controller passing on events based on the evaluation of an expression",
	"*", 17,
	(PropertyRNA *)&rna_Controller_name, (PropertyRNA *)&rna_Controller_rna_properties,
	&RNA_Controller,
	NULL,
	rna_Controller_refine,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	{NULL, NULL}
};

/* Python Controller */
static EnumPropertyItem rna_PythonController_mode_items[3] = {
	{0, "SCRIPT", 0, "Script", ""},
	{1, "MODULE", 0, "Module", ""},
	{0, NULL, 0, NULL, NULL}
};

EnumPropertyRNA rna_PythonController_mode = {
	{(PropertyRNA *)&rna_PythonController_text, NULL,
	-1, "mode", 3, "Execution Method",
	"Python script type (textblock or module - faster)",
	0, "*",
	PROP_ENUM, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 318767104, NULL, NULL,
	0, -1, NULL},
	PythonController_mode_get, PythonController_mode_set, NULL, NULL, NULL, NULL, rna_PythonController_mode_items, 2, 0
};

PointerPropertyRNA rna_PythonController_text = {
	{(PropertyRNA *)&rna_PythonController_module, (PropertyRNA *)&rna_PythonController_mode,
	-1, "text", 8388609, "Text",
	"Text data-block with the python script",
	0, "*",
	PROP_POINTER, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 318767104, NULL, NULL,
	0, -1, NULL},
	PythonController_text_get, PythonController_text_set, NULL, NULL,&RNA_Text
};

StringPropertyRNA rna_PythonController_module = {
	{(PropertyRNA *)&rna_PythonController_use_debug, (PropertyRNA *)&rna_PythonController_text,
	-1, "module", 262145, "Module",
	"Module name and function to run, e.g. \"someModule.main\" (internal texts and external python files can be used)",
	0, "*",
	PROP_STRING, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {64, 0, 0}, 0,
	NULL, 318767104, NULL, NULL,
	0, -1, NULL},
	PythonController_module_get, PythonController_module_length, PythonController_module_set, NULL, NULL, NULL, 64, ""
};

BoolPropertyRNA rna_PythonController_use_debug = {
	{NULL, (PropertyRNA *)&rna_PythonController_module,
	-1, "use_debug", 3, "D",
	"Continuously reload the module from disk for editing external modules without restarting",
	0, "*",
	PROP_BOOLEAN, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 318767104, NULL, NULL,
	0, -1, NULL},
	PythonController_use_debug_get, PythonController_use_debug_set, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL
};

StructRNA RNA_PythonController = {
	{(ContainerRNA *)&RNA_AndController, (ContainerRNA *)&RNA_ExpressionController,
	NULL,
	{(PropertyRNA *)&rna_PythonController_mode, (PropertyRNA *)&rna_PythonController_use_debug}},
	"PythonController", NULL, NULL, 4, "Python Controller",
	"Controller executing a python script",
	"*", 17,
	(PropertyRNA *)&rna_Controller_name, (PropertyRNA *)&rna_Controller_rna_properties,
	&RNA_Controller,
	NULL,
	rna_Controller_refine,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	{NULL, NULL}
};

/* And Controller */
StructRNA RNA_AndController = {
	{(ContainerRNA *)&RNA_OrController, (ContainerRNA *)&RNA_PythonController,
	NULL,
	{NULL, NULL}},
	"AndController", NULL, NULL, 4, "And Controller",
	"Controller passing on events based on a logical AND operation",
	"*", 17,
	(PropertyRNA *)&rna_Controller_name, (PropertyRNA *)&rna_Controller_rna_properties,
	&RNA_Controller,
	NULL,
	rna_Controller_refine,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	{NULL, NULL}
};

/* Or Controller */
StructRNA RNA_OrController = {
	{(ContainerRNA *)&RNA_NorController, (ContainerRNA *)&RNA_AndController,
	NULL,
	{NULL, NULL}},
	"OrController", NULL, NULL, 4, "Or Controller",
	"Controller passing on events based on a logical OR operation",
	"*", 17,
	(PropertyRNA *)&rna_Controller_name, (PropertyRNA *)&rna_Controller_rna_properties,
	&RNA_Controller,
	NULL,
	rna_Controller_refine,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	{NULL, NULL}
};

/* Nor Controller */
StructRNA RNA_NorController = {
	{(ContainerRNA *)&RNA_NandController, (ContainerRNA *)&RNA_OrController,
	NULL,
	{NULL, NULL}},
	"NorController", NULL, NULL, 4, "Nor Controller",
	"Controller passing on events based on a logical NOR operation",
	"*", 17,
	(PropertyRNA *)&rna_Controller_name, (PropertyRNA *)&rna_Controller_rna_properties,
	&RNA_Controller,
	NULL,
	rna_Controller_refine,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	{NULL, NULL}
};

/* Nand Controller */
StructRNA RNA_NandController = {
	{(ContainerRNA *)&RNA_XorController, (ContainerRNA *)&RNA_NorController,
	NULL,
	{NULL, NULL}},
	"NandController", NULL, NULL, 4, "Nand Controller",
	"Controller passing on events based on a logical NAND operation",
	"*", 17,
	(PropertyRNA *)&rna_Controller_name, (PropertyRNA *)&rna_Controller_rna_properties,
	&RNA_Controller,
	NULL,
	rna_Controller_refine,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	{NULL, NULL}
};

/* Xor Controller */
StructRNA RNA_XorController = {
	{(ContainerRNA *)&RNA_XnorController, (ContainerRNA *)&RNA_NandController,
	NULL,
	{NULL, NULL}},
	"XorController", NULL, NULL, 4, "Xor Controller",
	"Controller passing on events based on a logical XOR operation",
	"*", 17,
	(PropertyRNA *)&rna_Controller_name, (PropertyRNA *)&rna_Controller_rna_properties,
	&RNA_Controller,
	NULL,
	rna_Controller_refine,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	{NULL, NULL}
};

/* Xnor Controller */
StructRNA RNA_XnorController = {
	{(ContainerRNA *)&RNA_Curve, (ContainerRNA *)&RNA_XorController,
	NULL,
	{NULL, NULL}},
	"XnorController", NULL, NULL, 4, "Xnor Controller",
	"Controller passing on events based on a logical XNOR operation",
	"*", 17,
	(PropertyRNA *)&rna_Controller_name, (PropertyRNA *)&rna_Controller_rna_properties,
	&RNA_Controller,
	NULL,
	rna_Controller_refine,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	{NULL, NULL}
};

