
/* Automatically generated struct definitions for the Data API.
 * Do not edit manually, changes will be overwritten.           */

#define RNA_RUNTIME

#include <float.h>
#include <stdio.h>
#include <limits.h>
#include <string.h>

#include <stddef.h>

#include "MEM_guardedalloc.h"

#include "DNA_ID.h"
#include "DNA_scene_types.h"
#include "BLI_blenlib.h"

#include "BLI_utildefines.h"

#include "BKE_context.h"
#include "BKE_library.h"
#include "BKE_main.h"
#include "BKE_report.h"
#include "RNA_define.h"
#include "RNA_types.h"
#include "rna_internal.h"

#include "rna_prototypes_gen.h"

#include "rna_gpencil.c"

/* Autogenerated Functions */


extern CollectionPropertyRNA rna_ID_rna_properties;
extern PointerPropertyRNA rna_ID_rna_type;
extern StringPropertyRNA rna_ID_name;
extern IntPropertyRNA rna_ID_users;
extern BoolPropertyRNA rna_ID_use_fake_user;
extern BoolPropertyRNA rna_ID_tag;
extern BoolPropertyRNA rna_ID_is_updated;
extern BoolPropertyRNA rna_ID_is_updated_data;
extern BoolPropertyRNA rna_ID_is_library_indirect;
extern PointerPropertyRNA rna_ID_library;
extern PointerPropertyRNA rna_ID_preview;

CollectionPropertyRNA rna_GreasePencil_layers;
PointerPropertyRNA rna_GreasePencil_animation_data;
BoolPropertyRNA rna_GreasePencil_use_stroke_edit_mode;
BoolPropertyRNA rna_GreasePencil_use_onion_skinning;

extern FunctionRNA rna_ID_copy_func;
extern PointerPropertyRNA rna_ID_copy_id;

extern FunctionRNA rna_ID_user_clear_func;
extern FunctionRNA rna_ID_user_of_id_func;
extern PointerPropertyRNA rna_ID_user_of_id_id;
extern IntPropertyRNA rna_ID_user_of_id_count;

extern FunctionRNA rna_ID_animation_data_create_func;
extern PointerPropertyRNA rna_ID_animation_data_create_anim_data;

extern FunctionRNA rna_ID_animation_data_clear_func;
extern FunctionRNA rna_ID_update_tag_func;
extern EnumPropertyRNA rna_ID_update_tag_refresh;


extern FunctionRNA rna_GreasePencil_clear_func;


CollectionPropertyRNA rna_GreasePencilLayers_rna_properties;
PointerPropertyRNA rna_GreasePencilLayers_rna_type;
PointerPropertyRNA rna_GreasePencilLayers_active;
IntPropertyRNA rna_GreasePencilLayers_active_index;

extern FunctionRNA rna_GreasePencilLayers_new_func;
extern StringPropertyRNA rna_GreasePencilLayers_new_name;
extern BoolPropertyRNA rna_GreasePencilLayers_new_set_active;
extern PointerPropertyRNA rna_GreasePencilLayers_new_layer;

extern FunctionRNA rna_GreasePencilLayers_remove_func;
extern PointerPropertyRNA rna_GreasePencilLayers_remove_layer;



CollectionPropertyRNA rna_GPencilLayer_rna_properties;
PointerPropertyRNA rna_GPencilLayer_rna_type;
StringPropertyRNA rna_GPencilLayer_info;
CollectionPropertyRNA rna_GPencilLayer_frames;
PointerPropertyRNA rna_GPencilLayer_active_frame;
BoolPropertyRNA rna_GPencilLayer_use_volumetric_strokes;
FloatPropertyRNA rna_GPencilLayer_color;
FloatPropertyRNA rna_GPencilLayer_alpha;
FloatPropertyRNA rna_GPencilLayer_fill_color;
FloatPropertyRNA rna_GPencilLayer_fill_alpha;
IntPropertyRNA rna_GPencilLayer_line_width;
BoolPropertyRNA rna_GPencilLayer_use_onion_skinning;
IntPropertyRNA rna_GPencilLayer_ghost_before_range;
IntPropertyRNA rna_GPencilLayer_ghost_after_range;
BoolPropertyRNA rna_GPencilLayer_use_ghost_custom_colors;
FloatPropertyRNA rna_GPencilLayer_before_color;
FloatPropertyRNA rna_GPencilLayer_after_color;
BoolPropertyRNA rna_GPencilLayer_hide;
BoolPropertyRNA rna_GPencilLayer_lock;
BoolPropertyRNA rna_GPencilLayer_lock_frame;
BoolPropertyRNA rna_GPencilLayer_select;
BoolPropertyRNA rna_GPencilLayer_show_points;
BoolPropertyRNA rna_GPencilLayer_show_x_ray;
BoolPropertyRNA rna_GPencilLayer_is_stroke_visible;
BoolPropertyRNA rna_GPencilLayer_is_fill_visible;

extern FunctionRNA rna_GPencilLayer_clear_func;


CollectionPropertyRNA rna_GPencilFrames_rna_properties;
PointerPropertyRNA rna_GPencilFrames_rna_type;

extern FunctionRNA rna_GPencilFrames_new_func;
extern IntPropertyRNA rna_GPencilFrames_new_frame_number;
extern PointerPropertyRNA rna_GPencilFrames_new_frame;

extern FunctionRNA rna_GPencilFrames_remove_func;
extern PointerPropertyRNA rna_GPencilFrames_remove_frame;

extern FunctionRNA rna_GPencilFrames_copy_func;
extern PointerPropertyRNA rna_GPencilFrames_copy_source;
extern PointerPropertyRNA rna_GPencilFrames_copy_copy;



CollectionPropertyRNA rna_GPencilFrame_rna_properties;
PointerPropertyRNA rna_GPencilFrame_rna_type;
CollectionPropertyRNA rna_GPencilFrame_strokes;
IntPropertyRNA rna_GPencilFrame_frame_number;
BoolPropertyRNA rna_GPencilFrame_is_edited;
BoolPropertyRNA rna_GPencilFrame_select;

extern FunctionRNA rna_GPencilFrame_clear_func;


CollectionPropertyRNA rna_GPencilStrokes_rna_properties;
PointerPropertyRNA rna_GPencilStrokes_rna_type;

extern FunctionRNA rna_GPencilStrokes_new_func;
extern PointerPropertyRNA rna_GPencilStrokes_new_stroke;

extern FunctionRNA rna_GPencilStrokes_remove_func;
extern PointerPropertyRNA rna_GPencilStrokes_remove_stroke;



CollectionPropertyRNA rna_GPencilStroke_rna_properties;
PointerPropertyRNA rna_GPencilStroke_rna_type;
CollectionPropertyRNA rna_GPencilStroke_points;
EnumPropertyRNA rna_GPencilStroke_draw_mode;
BoolPropertyRNA rna_GPencilStroke_select;


CollectionPropertyRNA rna_GPencilStrokePoints_rna_properties;
PointerPropertyRNA rna_GPencilStrokePoints_rna_type;

extern FunctionRNA rna_GPencilStrokePoints_add_func;
extern IntPropertyRNA rna_GPencilStrokePoints_add_count;

extern FunctionRNA rna_GPencilStrokePoints_pop_func;
extern IntPropertyRNA rna_GPencilStrokePoints_pop_index;



CollectionPropertyRNA rna_GPencilStrokePoint_rna_properties;
PointerPropertyRNA rna_GPencilStrokePoint_rna_type;
FloatPropertyRNA rna_GPencilStrokePoint_co;
FloatPropertyRNA rna_GPencilStrokePoint_pressure;
BoolPropertyRNA rna_GPencilStrokePoint_select;

static PointerRNA GreasePencil_layers_get(CollectionPropertyIterator *iter)
{
	return rna_pointer_inherit_refine(&iter->parent, &RNA_GPencilLayer, rna_iterator_listbase_get(iter));
}

void GreasePencil_layers_begin(CollectionPropertyIterator *iter, PointerRNA *ptr)
{
	bGPdata *data = (bGPdata *)(ptr->data);

	memset(iter, 0, sizeof(*iter));
	iter->parent = *ptr;
	iter->prop = (PropertyRNA *)&rna_GreasePencil_layers;

	rna_iterator_listbase_begin(iter, &data->layers, NULL);

	if (iter->valid)
		iter->ptr = GreasePencil_layers_get(iter);
}

void GreasePencil_layers_next(CollectionPropertyIterator *iter)
{
	rna_iterator_listbase_next(iter);

	if (iter->valid)
		iter->ptr = GreasePencil_layers_get(iter);
}

void GreasePencil_layers_end(CollectionPropertyIterator *iter)
{
	rna_iterator_listbase_end(iter);
}

int GreasePencil_layers_lookup_int(PointerRNA *ptr, int index, PointerRNA *r_ptr)
{
	int found = 0;
	CollectionPropertyIterator iter;

	GreasePencil_layers_begin(&iter, ptr);

	if (iter.valid) {
		ListBaseIterator *internal = &iter.internal.listbase;
		if (internal->skip) {
			while (index-- > 0 && iter.valid) {
				rna_iterator_listbase_next(&iter);
			}
			found = (index == -1 && iter.valid);
		}
		else {
			while (index-- > 0 && internal->link)
				internal->link = internal->link->next;
			found = (index == -1 && internal->link);
		}
		if (found) *r_ptr = GreasePencil_layers_get(&iter);
	}

	GreasePencil_layers_end(&iter);

	return found;
}

int GreasePencil_layers_lookup_string(PointerRNA *ptr, const char *key, PointerRNA *r_ptr)
{
	extern int GPencilLayer_info_length(PointerRNA *);
	extern void GPencilLayer_info_get(PointerRNA *, char *);

	bool found = false;
	CollectionPropertyIterator iter;
	char namebuf[1024];
	char *name;

	GreasePencil_layers_begin(&iter, ptr);

	while (iter.valid) {
		if (iter.ptr.data) {
			int namelen = GPencilLayer_info_length(&iter.ptr);
			if (namelen < 1024) {
				GPencilLayer_info_get(&iter.ptr, namebuf);
				if (strcmp(namebuf, key) == 0) {
					found = true;
					*r_ptr = iter.ptr;
					break;
				}
			}
			else {
				name = MEM_mallocN(namelen+1, "name string");
				GPencilLayer_info_get(&iter.ptr, name);
				if (strcmp(name, key) == 0) {
					MEM_freeN(name);

					found = true;
					*r_ptr = iter.ptr;
					break;
				}
				else {
					MEM_freeN(name);
				}
			}
		}
		GreasePencil_layers_next(&iter);
	}
	GreasePencil_layers_end(&iter);

	return found;
}

PointerRNA GreasePencil_animation_data_get(PointerRNA *ptr)
{
	bGPdata *data = (bGPdata *)(ptr->data);
	return rna_pointer_inherit_refine(ptr, &RNA_AnimData, data->adt);
}

int GreasePencil_use_stroke_edit_mode_get(PointerRNA *ptr)
{
	bGPdata *data = (bGPdata *)(ptr->data);
	return (((data->flag) & 256) != 0);
}

void GreasePencil_use_stroke_edit_mode_set(PointerRNA *ptr, int value)
{
	bGPdata *data = (bGPdata *)(ptr->data);
	if (value) data->flag |= 256;
	else data->flag &= ~256;
}

int GreasePencil_use_onion_skinning_get(PointerRNA *ptr)
{
	bGPdata *data = (bGPdata *)(ptr->data);
	return (((data->flag) & 512) != 0);
}

void GreasePencil_use_onion_skinning_set(PointerRNA *ptr, int value)
{
	rna_GPencil_use_onion_skinning_set(ptr, value);
}

static PointerRNA GreasePencilLayers_rna_properties_get(CollectionPropertyIterator *iter)
{
	return rna_builtin_properties_get(iter);
}

void GreasePencilLayers_rna_properties_begin(CollectionPropertyIterator *iter, PointerRNA *ptr)
{

	memset(iter, 0, sizeof(*iter));
	iter->parent = *ptr;
	iter->prop = (PropertyRNA *)&rna_GreasePencilLayers_rna_properties;

	rna_builtin_properties_begin(iter, ptr);

	if (iter->valid)
		iter->ptr = GreasePencilLayers_rna_properties_get(iter);
}

void GreasePencilLayers_rna_properties_next(CollectionPropertyIterator *iter)
{
	rna_builtin_properties_next(iter);

	if (iter->valid)
		iter->ptr = GreasePencilLayers_rna_properties_get(iter);
}

void GreasePencilLayers_rna_properties_end(CollectionPropertyIterator *iter)
{
	rna_iterator_listbase_end(iter);
}

int GreasePencilLayers_rna_properties_lookup_string(PointerRNA *ptr, const char *key, PointerRNA *r_ptr)
{
	return rna_builtin_properties_lookup_string(ptr, key, r_ptr);
}

PointerRNA GreasePencilLayers_rna_type_get(PointerRNA *ptr)
{
	return rna_builtin_type_get(ptr);
}

PointerRNA GreasePencilLayers_active_get(PointerRNA *ptr)
{
	return rna_GPencil_active_layer_get(ptr);
}

void GreasePencilLayers_active_set(PointerRNA *ptr, PointerRNA value)
{
	rna_GPencil_active_layer_set(ptr, value);
}

int GreasePencilLayers_active_index_get(PointerRNA *ptr)
{
	return rna_GPencil_active_layer_index_get(ptr);
}

void GreasePencilLayers_active_index_set(PointerRNA *ptr, int value)
{
	rna_GPencil_active_layer_index_set(ptr, value);
}

static PointerRNA GPencilLayer_rna_properties_get(CollectionPropertyIterator *iter)
{
	return rna_builtin_properties_get(iter);
}

void GPencilLayer_rna_properties_begin(CollectionPropertyIterator *iter, PointerRNA *ptr)
{

	memset(iter, 0, sizeof(*iter));
	iter->parent = *ptr;
	iter->prop = (PropertyRNA *)&rna_GPencilLayer_rna_properties;

	rna_builtin_properties_begin(iter, ptr);

	if (iter->valid)
		iter->ptr = GPencilLayer_rna_properties_get(iter);
}

void GPencilLayer_rna_properties_next(CollectionPropertyIterator *iter)
{
	rna_builtin_properties_next(iter);

	if (iter->valid)
		iter->ptr = GPencilLayer_rna_properties_get(iter);
}

void GPencilLayer_rna_properties_end(CollectionPropertyIterator *iter)
{
	rna_iterator_listbase_end(iter);
}

int GPencilLayer_rna_properties_lookup_string(PointerRNA *ptr, const char *key, PointerRNA *r_ptr)
{
	return rna_builtin_properties_lookup_string(ptr, key, r_ptr);
}

PointerRNA GPencilLayer_rna_type_get(PointerRNA *ptr)
{
	return rna_builtin_type_get(ptr);
}

void GPencilLayer_info_get(PointerRNA *ptr, char *value)
{
	bGPDlayer *data = (bGPDlayer *)(ptr->data);
	BLI_strncpy_utf8(value, data->info, 128);
}

int GPencilLayer_info_length(PointerRNA *ptr)
{
	bGPDlayer *data = (bGPDlayer *)(ptr->data);
	return strlen(data->info);
}

void GPencilLayer_info_set(PointerRNA *ptr, const char *value)
{
	rna_GPencilLayer_info_set(ptr, value);
}

static PointerRNA GPencilLayer_frames_get(CollectionPropertyIterator *iter)
{
	return rna_pointer_inherit_refine(&iter->parent, &RNA_GPencilFrame, rna_iterator_listbase_get(iter));
}

void GPencilLayer_frames_begin(CollectionPropertyIterator *iter, PointerRNA *ptr)
{
	bGPDlayer *data = (bGPDlayer *)(ptr->data);

	memset(iter, 0, sizeof(*iter));
	iter->parent = *ptr;
	iter->prop = (PropertyRNA *)&rna_GPencilLayer_frames;

	rna_iterator_listbase_begin(iter, &data->frames, NULL);

	if (iter->valid)
		iter->ptr = GPencilLayer_frames_get(iter);
}

void GPencilLayer_frames_next(CollectionPropertyIterator *iter)
{
	rna_iterator_listbase_next(iter);

	if (iter->valid)
		iter->ptr = GPencilLayer_frames_get(iter);
}

void GPencilLayer_frames_end(CollectionPropertyIterator *iter)
{
	rna_iterator_listbase_end(iter);
}

int GPencilLayer_frames_lookup_int(PointerRNA *ptr, int index, PointerRNA *r_ptr)
{
	int found = 0;
	CollectionPropertyIterator iter;

	GPencilLayer_frames_begin(&iter, ptr);

	if (iter.valid) {
		ListBaseIterator *internal = &iter.internal.listbase;
		if (internal->skip) {
			while (index-- > 0 && iter.valid) {
				rna_iterator_listbase_next(&iter);
			}
			found = (index == -1 && iter.valid);
		}
		else {
			while (index-- > 0 && internal->link)
				internal->link = internal->link->next;
			found = (index == -1 && internal->link);
		}
		if (found) *r_ptr = GPencilLayer_frames_get(&iter);
	}

	GPencilLayer_frames_end(&iter);

	return found;
}

PointerRNA GPencilLayer_active_frame_get(PointerRNA *ptr)
{
	bGPDlayer *data = (bGPDlayer *)(ptr->data);
	return rna_pointer_inherit_refine(ptr, &RNA_GPencilFrame, data->actframe);
}

int GPencilLayer_use_volumetric_strokes_get(PointerRNA *ptr)
{
	bGPDlayer *data = (bGPDlayer *)(ptr->data);
	return (((data->flag) & 1024) != 0);
}

void GPencilLayer_use_volumetric_strokes_set(PointerRNA *ptr, int value)
{
	bGPDlayer *data = (bGPDlayer *)(ptr->data);
	if (value) data->flag |= 1024;
	else data->flag &= ~1024;
}

void GPencilLayer_color_get(PointerRNA *ptr, float values[3])
{
	bGPDlayer *data = (bGPDlayer *)(ptr->data);
	unsigned int i;

	for (i = 0; i < 3; i++) {
		values[i] = (float)(((float *)data->color)[i]);
	}
}

void GPencilLayer_color_set(PointerRNA *ptr, const float values[3])
{
	bGPDlayer *data = (bGPDlayer *)(ptr->data);
	unsigned int i;

	for (i = 0; i < 3; i++) {
		((float *)data->color)[i] = CLAMPIS(values[i], 0.0f, 1.0f);
	}
}

float GPencilLayer_alpha_get(PointerRNA *ptr)
{
	bGPDlayer *data = (bGPDlayer *)(ptr->data);
	return (float)(data->color[3]);
}

void GPencilLayer_alpha_set(PointerRNA *ptr, float value)
{
	bGPDlayer *data = (bGPDlayer *)(ptr->data);
	data->color[3] = CLAMPIS(value, 0.0f, 1.0f);
}

void GPencilLayer_fill_color_get(PointerRNA *ptr, float values[3])
{
	bGPDlayer *data = (bGPDlayer *)(ptr->data);
	unsigned int i;

	for (i = 0; i < 3; i++) {
		values[i] = (float)(((float *)data->fill)[i]);
	}
}

void GPencilLayer_fill_color_set(PointerRNA *ptr, const float values[3])
{
	bGPDlayer *data = (bGPDlayer *)(ptr->data);
	unsigned int i;

	for (i = 0; i < 3; i++) {
		((float *)data->fill)[i] = CLAMPIS(values[i], 0.0f, 1.0f);
	}
}

float GPencilLayer_fill_alpha_get(PointerRNA *ptr)
{
	bGPDlayer *data = (bGPDlayer *)(ptr->data);
	return (float)(data->fill[3]);
}

void GPencilLayer_fill_alpha_set(PointerRNA *ptr, float value)
{
	bGPDlayer *data = (bGPDlayer *)(ptr->data);
	data->fill[3] = CLAMPIS(value, 0.0f, 1.0f);
}

int GPencilLayer_line_width_get(PointerRNA *ptr)
{
	bGPDlayer *data = (bGPDlayer *)(ptr->data);
	return (int)(data->thickness);
}

void GPencilLayer_line_width_set(PointerRNA *ptr, int value)
{
	bGPDlayer *data = (bGPDlayer *)(ptr->data);
	int prop_clamp_min = INT_MIN, prop_clamp_max = INT_MAX, prop_soft_min, prop_soft_max;
	rna_GPencilLayer_line_width_range(ptr, &prop_clamp_min, &prop_clamp_max, &prop_soft_min, &prop_soft_max);
	data->thickness = CLAMPIS(value, prop_clamp_min, prop_clamp_max);}

int GPencilLayer_use_onion_skinning_get(PointerRNA *ptr)
{
	bGPDlayer *data = (bGPDlayer *)(ptr->data);
	return (((data->flag) & 16) != 0);
}

void GPencilLayer_use_onion_skinning_set(PointerRNA *ptr, int value)
{
	bGPDlayer *data = (bGPDlayer *)(ptr->data);
	if (value) data->flag |= 16;
	else data->flag &= ~16;
}

int GPencilLayer_ghost_before_range_get(PointerRNA *ptr)
{
	bGPDlayer *data = (bGPDlayer *)(ptr->data);
	return (int)(data->gstep);
}

void GPencilLayer_ghost_before_range_set(PointerRNA *ptr, int value)
{
	bGPDlayer *data = (bGPDlayer *)(ptr->data);
	data->gstep = CLAMPIS(value, 0, 120);
}

int GPencilLayer_ghost_after_range_get(PointerRNA *ptr)
{
	bGPDlayer *data = (bGPDlayer *)(ptr->data);
	return (int)(data->gstep_next);
}

void GPencilLayer_ghost_after_range_set(PointerRNA *ptr, int value)
{
	bGPDlayer *data = (bGPDlayer *)(ptr->data);
	data->gstep_next = CLAMPIS(value, 0, 120);
}

int GPencilLayer_use_ghost_custom_colors_get(PointerRNA *ptr)
{
	bGPDlayer *data = (bGPDlayer *)(ptr->data);
	return (((data->flag) & 768) != 0);
}

void GPencilLayer_use_ghost_custom_colors_set(PointerRNA *ptr, int value)
{
	bGPDlayer *data = (bGPDlayer *)(ptr->data);
	if (value) data->flag |= 768;
	else data->flag &= ~768;
}

void GPencilLayer_before_color_get(PointerRNA *ptr, float values[3])
{
	bGPDlayer *data = (bGPDlayer *)(ptr->data);
	unsigned int i;

	for (i = 0; i < 3; i++) {
		values[i] = (float)(((float *)data->gcolor_prev)[i]);
	}
}

void GPencilLayer_before_color_set(PointerRNA *ptr, const float values[3])
{
	bGPDlayer *data = (bGPDlayer *)(ptr->data);
	unsigned int i;

	for (i = 0; i < 3; i++) {
		((float *)data->gcolor_prev)[i] = CLAMPIS(values[i], 0.0f, 1.0f);
	}
}

void GPencilLayer_after_color_get(PointerRNA *ptr, float values[3])
{
	bGPDlayer *data = (bGPDlayer *)(ptr->data);
	unsigned int i;

	for (i = 0; i < 3; i++) {
		values[i] = (float)(((float *)data->gcolor_next)[i]);
	}
}

void GPencilLayer_after_color_set(PointerRNA *ptr, const float values[3])
{
	bGPDlayer *data = (bGPDlayer *)(ptr->data);
	unsigned int i;

	for (i = 0; i < 3; i++) {
		((float *)data->gcolor_next)[i] = CLAMPIS(values[i], 0.0f, 1.0f);
	}
}

int GPencilLayer_hide_get(PointerRNA *ptr)
{
	bGPDlayer *data = (bGPDlayer *)(ptr->data);
	return (((data->flag) & 1) != 0);
}

void GPencilLayer_hide_set(PointerRNA *ptr, int value)
{
	bGPDlayer *data = (bGPDlayer *)(ptr->data);
	if (value) data->flag |= 1;
	else data->flag &= ~1;
}

int GPencilLayer_lock_get(PointerRNA *ptr)
{
	bGPDlayer *data = (bGPDlayer *)(ptr->data);
	return (((data->flag) & 2) != 0);
}

void GPencilLayer_lock_set(PointerRNA *ptr, int value)
{
	bGPDlayer *data = (bGPDlayer *)(ptr->data);
	if (value) data->flag |= 2;
	else data->flag &= ~2;
}

int GPencilLayer_lock_frame_get(PointerRNA *ptr)
{
	bGPDlayer *data = (bGPDlayer *)(ptr->data);
	return (((data->flag) & 64) != 0);
}

void GPencilLayer_lock_frame_set(PointerRNA *ptr, int value)
{
	bGPDlayer *data = (bGPDlayer *)(ptr->data);
	if (value) data->flag |= 64;
	else data->flag &= ~64;
}

int GPencilLayer_select_get(PointerRNA *ptr)
{
	bGPDlayer *data = (bGPDlayer *)(ptr->data);
	return (((data->flag) & 32) != 0);
}

void GPencilLayer_select_set(PointerRNA *ptr, int value)
{
	bGPDlayer *data = (bGPDlayer *)(ptr->data);
	if (value) data->flag |= 32;
	else data->flag &= ~32;
}

int GPencilLayer_show_points_get(PointerRNA *ptr)
{
	bGPDlayer *data = (bGPDlayer *)(ptr->data);
	return (((data->flag) & 8) != 0);
}

void GPencilLayer_show_points_set(PointerRNA *ptr, int value)
{
	bGPDlayer *data = (bGPDlayer *)(ptr->data);
	if (value) data->flag |= 8;
	else data->flag &= ~8;
}

int GPencilLayer_show_x_ray_get(PointerRNA *ptr)
{
	bGPDlayer *data = (bGPDlayer *)(ptr->data);
	return !(((data->flag) & 128) != 0);
}

void GPencilLayer_show_x_ray_set(PointerRNA *ptr, int value)
{
	bGPDlayer *data = (bGPDlayer *)(ptr->data);
	if (!value) data->flag |= 128;
	else data->flag &= ~128;
}

int GPencilLayer_is_stroke_visible_get(PointerRNA *ptr)
{
	return rna_GPencilLayer_is_stroke_visible_get(ptr);
}

int GPencilLayer_is_fill_visible_get(PointerRNA *ptr)
{
	return rna_GPencilLayer_is_fill_visible_get(ptr);
}

static PointerRNA GPencilFrames_rna_properties_get(CollectionPropertyIterator *iter)
{
	return rna_builtin_properties_get(iter);
}

void GPencilFrames_rna_properties_begin(CollectionPropertyIterator *iter, PointerRNA *ptr)
{

	memset(iter, 0, sizeof(*iter));
	iter->parent = *ptr;
	iter->prop = (PropertyRNA *)&rna_GPencilFrames_rna_properties;

	rna_builtin_properties_begin(iter, ptr);

	if (iter->valid)
		iter->ptr = GPencilFrames_rna_properties_get(iter);
}

void GPencilFrames_rna_properties_next(CollectionPropertyIterator *iter)
{
	rna_builtin_properties_next(iter);

	if (iter->valid)
		iter->ptr = GPencilFrames_rna_properties_get(iter);
}

void GPencilFrames_rna_properties_end(CollectionPropertyIterator *iter)
{
	rna_iterator_listbase_end(iter);
}

int GPencilFrames_rna_properties_lookup_string(PointerRNA *ptr, const char *key, PointerRNA *r_ptr)
{
	return rna_builtin_properties_lookup_string(ptr, key, r_ptr);
}

PointerRNA GPencilFrames_rna_type_get(PointerRNA *ptr)
{
	return rna_builtin_type_get(ptr);
}

static PointerRNA GPencilFrame_rna_properties_get(CollectionPropertyIterator *iter)
{
	return rna_builtin_properties_get(iter);
}

void GPencilFrame_rna_properties_begin(CollectionPropertyIterator *iter, PointerRNA *ptr)
{

	memset(iter, 0, sizeof(*iter));
	iter->parent = *ptr;
	iter->prop = (PropertyRNA *)&rna_GPencilFrame_rna_properties;

	rna_builtin_properties_begin(iter, ptr);

	if (iter->valid)
		iter->ptr = GPencilFrame_rna_properties_get(iter);
}

void GPencilFrame_rna_properties_next(CollectionPropertyIterator *iter)
{
	rna_builtin_properties_next(iter);

	if (iter->valid)
		iter->ptr = GPencilFrame_rna_properties_get(iter);
}

void GPencilFrame_rna_properties_end(CollectionPropertyIterator *iter)
{
	rna_iterator_listbase_end(iter);
}

int GPencilFrame_rna_properties_lookup_string(PointerRNA *ptr, const char *key, PointerRNA *r_ptr)
{
	return rna_builtin_properties_lookup_string(ptr, key, r_ptr);
}

PointerRNA GPencilFrame_rna_type_get(PointerRNA *ptr)
{
	return rna_builtin_type_get(ptr);
}

static PointerRNA GPencilFrame_strokes_get(CollectionPropertyIterator *iter)
{
	return rna_pointer_inherit_refine(&iter->parent, &RNA_GPencilStroke, rna_iterator_listbase_get(iter));
}

void GPencilFrame_strokes_begin(CollectionPropertyIterator *iter, PointerRNA *ptr)
{
	bGPDframe *data = (bGPDframe *)(ptr->data);

	memset(iter, 0, sizeof(*iter));
	iter->parent = *ptr;
	iter->prop = (PropertyRNA *)&rna_GPencilFrame_strokes;

	rna_iterator_listbase_begin(iter, &data->strokes, NULL);

	if (iter->valid)
		iter->ptr = GPencilFrame_strokes_get(iter);
}

void GPencilFrame_strokes_next(CollectionPropertyIterator *iter)
{
	rna_iterator_listbase_next(iter);

	if (iter->valid)
		iter->ptr = GPencilFrame_strokes_get(iter);
}

void GPencilFrame_strokes_end(CollectionPropertyIterator *iter)
{
	rna_iterator_listbase_end(iter);
}

int GPencilFrame_strokes_lookup_int(PointerRNA *ptr, int index, PointerRNA *r_ptr)
{
	int found = 0;
	CollectionPropertyIterator iter;

	GPencilFrame_strokes_begin(&iter, ptr);

	if (iter.valid) {
		ListBaseIterator *internal = &iter.internal.listbase;
		if (internal->skip) {
			while (index-- > 0 && iter.valid) {
				rna_iterator_listbase_next(&iter);
			}
			found = (index == -1 && iter.valid);
		}
		else {
			while (index-- > 0 && internal->link)
				internal->link = internal->link->next;
			found = (index == -1 && internal->link);
		}
		if (found) *r_ptr = GPencilFrame_strokes_get(&iter);
	}

	GPencilFrame_strokes_end(&iter);

	return found;
}

int GPencilFrame_frame_number_get(PointerRNA *ptr)
{
	bGPDframe *data = (bGPDframe *)(ptr->data);
	return (int)(data->framenum);
}

void GPencilFrame_frame_number_set(PointerRNA *ptr, int value)
{
	bGPDframe *data = (bGPDframe *)(ptr->data);
	data->framenum = CLAMPIS(value, -300000, 300000);
}

int GPencilFrame_is_edited_get(PointerRNA *ptr)
{
	bGPDframe *data = (bGPDframe *)(ptr->data);
	return (((data->flag) & 1) != 0);
}

void GPencilFrame_is_edited_set(PointerRNA *ptr, int value)
{
	bGPDframe *data = (bGPDframe *)(ptr->data);
	if (value) data->flag |= 1;
	else data->flag &= ~1;
}

int GPencilFrame_select_get(PointerRNA *ptr)
{
	bGPDframe *data = (bGPDframe *)(ptr->data);
	return (((data->flag) & 2) != 0);
}

void GPencilFrame_select_set(PointerRNA *ptr, int value)
{
	bGPDframe *data = (bGPDframe *)(ptr->data);
	if (value) data->flag |= 2;
	else data->flag &= ~2;
}

static PointerRNA GPencilStrokes_rna_properties_get(CollectionPropertyIterator *iter)
{
	return rna_builtin_properties_get(iter);
}

void GPencilStrokes_rna_properties_begin(CollectionPropertyIterator *iter, PointerRNA *ptr)
{

	memset(iter, 0, sizeof(*iter));
	iter->parent = *ptr;
	iter->prop = (PropertyRNA *)&rna_GPencilStrokes_rna_properties;

	rna_builtin_properties_begin(iter, ptr);

	if (iter->valid)
		iter->ptr = GPencilStrokes_rna_properties_get(iter);
}

void GPencilStrokes_rna_properties_next(CollectionPropertyIterator *iter)
{
	rna_builtin_properties_next(iter);

	if (iter->valid)
		iter->ptr = GPencilStrokes_rna_properties_get(iter);
}

void GPencilStrokes_rna_properties_end(CollectionPropertyIterator *iter)
{
	rna_iterator_listbase_end(iter);
}

int GPencilStrokes_rna_properties_lookup_string(PointerRNA *ptr, const char *key, PointerRNA *r_ptr)
{
	return rna_builtin_properties_lookup_string(ptr, key, r_ptr);
}

PointerRNA GPencilStrokes_rna_type_get(PointerRNA *ptr)
{
	return rna_builtin_type_get(ptr);
}

static PointerRNA GPencilStroke_rna_properties_get(CollectionPropertyIterator *iter)
{
	return rna_builtin_properties_get(iter);
}

void GPencilStroke_rna_properties_begin(CollectionPropertyIterator *iter, PointerRNA *ptr)
{

	memset(iter, 0, sizeof(*iter));
	iter->parent = *ptr;
	iter->prop = (PropertyRNA *)&rna_GPencilStroke_rna_properties;

	rna_builtin_properties_begin(iter, ptr);

	if (iter->valid)
		iter->ptr = GPencilStroke_rna_properties_get(iter);
}

void GPencilStroke_rna_properties_next(CollectionPropertyIterator *iter)
{
	rna_builtin_properties_next(iter);

	if (iter->valid)
		iter->ptr = GPencilStroke_rna_properties_get(iter);
}

void GPencilStroke_rna_properties_end(CollectionPropertyIterator *iter)
{
	rna_iterator_listbase_end(iter);
}

int GPencilStroke_rna_properties_lookup_string(PointerRNA *ptr, const char *key, PointerRNA *r_ptr)
{
	return rna_builtin_properties_lookup_string(ptr, key, r_ptr);
}

PointerRNA GPencilStroke_rna_type_get(PointerRNA *ptr)
{
	return rna_builtin_type_get(ptr);
}

int GPencilStroke_points_length(PointerRNA *ptr)
{
	bGPDstroke *data = (bGPDstroke *)(ptr->data);
	return (data->points == NULL) ? 0 : data->totpoints;
}

static PointerRNA GPencilStroke_points_get(CollectionPropertyIterator *iter)
{
	return rna_pointer_inherit_refine(&iter->parent, &RNA_GPencilStrokePoint, rna_iterator_array_get(iter));
}

void GPencilStroke_points_begin(CollectionPropertyIterator *iter, PointerRNA *ptr)
{
	bGPDstroke *data = (bGPDstroke *)(ptr->data);

	memset(iter, 0, sizeof(*iter));
	iter->parent = *ptr;
	iter->prop = (PropertyRNA *)&rna_GPencilStroke_points;

	rna_iterator_array_begin(iter, data->points, sizeof(data->points[0]), data->totpoints, 0, NULL);

	if (iter->valid)
		iter->ptr = GPencilStroke_points_get(iter);
}

void GPencilStroke_points_next(CollectionPropertyIterator *iter)
{
	rna_iterator_array_next(iter);

	if (iter->valid)
		iter->ptr = GPencilStroke_points_get(iter);
}

void GPencilStroke_points_end(CollectionPropertyIterator *iter)
{
	rna_iterator_array_end(iter);
}

int GPencilStroke_points_lookup_int(PointerRNA *ptr, int index, PointerRNA *r_ptr)
{
	int found = 0;
	CollectionPropertyIterator iter;

	GPencilStroke_points_begin(&iter, ptr);

	if (iter.valid) {
		ArrayIterator *internal = &iter.internal.array;
		if (index < 0 || index >= internal->length) {
#ifdef __GNUC__
			printf("Array iterator out of range: %s (index %d)\n", __func__, index);
#else
			printf("Array iterator out of range: (index %d)\n", index);
#endif
		}
		else if (internal->skip) {
			while (index-- > 0 && iter.valid) {
				rna_iterator_array_next(&iter);
			}
			found = (index == -1 && iter.valid);
		}
		else {
			internal->ptr += internal->itemsize * index;
			found = 1;
		}
		if (found) *r_ptr = GPencilStroke_points_get(&iter);
	}

	GPencilStroke_points_end(&iter);

	return found;
}

int GPencilStroke_draw_mode_get(PointerRNA *ptr)
{
	bGPDstroke *data = (bGPDstroke *)(ptr->data);
	return ((data->flag) & 7);
}

void GPencilStroke_draw_mode_set(PointerRNA *ptr, int value)
{
	bGPDstroke *data = (bGPDstroke *)(ptr->data);
	data->flag &= ~7;
	data->flag |= value;
}

int GPencilStroke_select_get(PointerRNA *ptr)
{
	bGPDstroke *data = (bGPDstroke *)(ptr->data);
	return (((data->flag) & 8) != 0);
}

void GPencilStroke_select_set(PointerRNA *ptr, int value)
{
	rna_GPencil_stroke_select_set(ptr, value);
}

static PointerRNA GPencilStrokePoints_rna_properties_get(CollectionPropertyIterator *iter)
{
	return rna_builtin_properties_get(iter);
}

void GPencilStrokePoints_rna_properties_begin(CollectionPropertyIterator *iter, PointerRNA *ptr)
{

	memset(iter, 0, sizeof(*iter));
	iter->parent = *ptr;
	iter->prop = (PropertyRNA *)&rna_GPencilStrokePoints_rna_properties;

	rna_builtin_properties_begin(iter, ptr);

	if (iter->valid)
		iter->ptr = GPencilStrokePoints_rna_properties_get(iter);
}

void GPencilStrokePoints_rna_properties_next(CollectionPropertyIterator *iter)
{
	rna_builtin_properties_next(iter);

	if (iter->valid)
		iter->ptr = GPencilStrokePoints_rna_properties_get(iter);
}

void GPencilStrokePoints_rna_properties_end(CollectionPropertyIterator *iter)
{
	rna_iterator_listbase_end(iter);
}

int GPencilStrokePoints_rna_properties_lookup_string(PointerRNA *ptr, const char *key, PointerRNA *r_ptr)
{
	return rna_builtin_properties_lookup_string(ptr, key, r_ptr);
}

PointerRNA GPencilStrokePoints_rna_type_get(PointerRNA *ptr)
{
	return rna_builtin_type_get(ptr);
}

static PointerRNA GPencilStrokePoint_rna_properties_get(CollectionPropertyIterator *iter)
{
	return rna_builtin_properties_get(iter);
}

void GPencilStrokePoint_rna_properties_begin(CollectionPropertyIterator *iter, PointerRNA *ptr)
{

	memset(iter, 0, sizeof(*iter));
	iter->parent = *ptr;
	iter->prop = (PropertyRNA *)&rna_GPencilStrokePoint_rna_properties;

	rna_builtin_properties_begin(iter, ptr);

	if (iter->valid)
		iter->ptr = GPencilStrokePoint_rna_properties_get(iter);
}

void GPencilStrokePoint_rna_properties_next(CollectionPropertyIterator *iter)
{
	rna_builtin_properties_next(iter);

	if (iter->valid)
		iter->ptr = GPencilStrokePoint_rna_properties_get(iter);
}

void GPencilStrokePoint_rna_properties_end(CollectionPropertyIterator *iter)
{
	rna_iterator_listbase_end(iter);
}

int GPencilStrokePoint_rna_properties_lookup_string(PointerRNA *ptr, const char *key, PointerRNA *r_ptr)
{
	return rna_builtin_properties_lookup_string(ptr, key, r_ptr);
}

PointerRNA GPencilStrokePoint_rna_type_get(PointerRNA *ptr)
{
	return rna_builtin_type_get(ptr);
}

void GPencilStrokePoint_co_get(PointerRNA *ptr, float values[3])
{
	bGPDspoint *data = (bGPDspoint *)(ptr->data);
	unsigned int i;

	for (i = 0; i < 3; i++) {
		values[i] = (float)((&data->x)[i]);
	}
}

void GPencilStrokePoint_co_set(PointerRNA *ptr, const float values[3])
{
	bGPDspoint *data = (bGPDspoint *)(ptr->data);
	unsigned int i;

	for (i = 0; i < 3; i++) {
		(&data->x)[i] = values[i];
	}
}

float GPencilStrokePoint_pressure_get(PointerRNA *ptr)
{
	bGPDspoint *data = (bGPDspoint *)(ptr->data);
	return (float)(data->pressure);
}

void GPencilStrokePoint_pressure_set(PointerRNA *ptr, float value)
{
	bGPDspoint *data = (bGPDspoint *)(ptr->data);
	data->pressure = CLAMPIS(value, 0.0f, 1.0f);
}

int GPencilStrokePoint_select_get(PointerRNA *ptr)
{
	bGPDspoint *data = (bGPDspoint *)(ptr->data);
	return (((data->flag) & 1) != 0);
}

void GPencilStrokePoint_select_set(PointerRNA *ptr, int value)
{
	rna_GPencil_stroke_point_select_set(ptr, value);
}

void GreasePencil_clear(struct bGPdata *_self)
{
	rna_GPencil_clear(_self);
}

void GreasePencil_clear_call(bContext *C, ReportList *reports, PointerRNA *_ptr, ParameterList *_parms)
{
	struct bGPdata *_self;
	_self = (struct bGPdata *)_ptr->data;
	
	rna_GPencil_clear(_self);
}

/* Repeated prototypes to detect errors */

void rna_GPencil_clear(struct bGPdata *_self);

struct bGPDlayer *GreasePencilLayers_new(struct bGPdata *_self, const char * name, int set_active)
{
	return rna_GPencil_layer_new(_self, name, set_active);
}

void GreasePencilLayers_new_call(bContext *C, ReportList *reports, PointerRNA *_ptr, ParameterList *_parms)
{
	struct bGPdata *_self;
	const char * name;
	int set_active;
	struct bGPDlayer *layer;
	char *_data, *_retdata;
	
	_self = (struct bGPdata *)_ptr->data;
	_data = (char *)_parms->data;
	name = *((const char * *)_data);
	_data += 8;
	set_active = *((int *)_data);
	_data += 4;
	_retdata = _data;
	
	layer = rna_GPencil_layer_new(_self, name, set_active);
	*((struct bGPDlayer **)_retdata) = layer;
}

void GreasePencilLayers_remove(struct bGPdata *_self, ReportList *reports, struct PointerRNA *layer)
{
	rna_GPencil_layer_remove(_self, reports, layer);
}

void GreasePencilLayers_remove_call(bContext *C, ReportList *reports, PointerRNA *_ptr, ParameterList *_parms)
{
	struct bGPdata *_self;
	struct PointerRNA *layer;
	char *_data;
	
	_self = (struct bGPdata *)_ptr->data;
	_data = (char *)_parms->data;
	layer = *((struct PointerRNA **)_data);
	
	rna_GPencil_layer_remove(_self, reports, layer);
}

/* Repeated prototypes to detect errors */

struct bGPDlayer *rna_GPencil_layer_new(struct bGPdata *_self, const char * name, int set_active);
void rna_GPencil_layer_remove(struct bGPdata *_self, ReportList *reports, struct PointerRNA *layer);

void GPencilLayer_clear(struct bGPDlayer *_self)
{
	rna_GPencil_layer_clear(_self);
}

void GPencilLayer_clear_call(bContext *C, ReportList *reports, PointerRNA *_ptr, ParameterList *_parms)
{
	struct bGPDlayer *_self;
	_self = (struct bGPDlayer *)_ptr->data;
	
	rna_GPencil_layer_clear(_self);
}

/* Repeated prototypes to detect errors */

void rna_GPencil_layer_clear(struct bGPDlayer *_self);

struct bGPDframe *GPencilFrames_new(struct bGPDlayer *_self, ReportList *reports, int frame_number)
{
	return rna_GPencil_frame_new(_self, reports, frame_number);
}

void GPencilFrames_new_call(bContext *C, ReportList *reports, PointerRNA *_ptr, ParameterList *_parms)
{
	struct bGPDlayer *_self;
	int frame_number;
	struct bGPDframe *frame;
	char *_data, *_retdata;
	
	_self = (struct bGPDlayer *)_ptr->data;
	_data = (char *)_parms->data;
	frame_number = *((int *)_data);
	_data += 4;
	_retdata = _data;
	
	frame = rna_GPencil_frame_new(_self, reports, frame_number);
	*((struct bGPDframe **)_retdata) = frame;
}

void GPencilFrames_remove(struct bGPDlayer *_self, ReportList *reports, struct PointerRNA *frame)
{
	rna_GPencil_frame_remove(_self, reports, frame);
}

void GPencilFrames_remove_call(bContext *C, ReportList *reports, PointerRNA *_ptr, ParameterList *_parms)
{
	struct bGPDlayer *_self;
	struct PointerRNA *frame;
	char *_data;
	
	_self = (struct bGPDlayer *)_ptr->data;
	_data = (char *)_parms->data;
	frame = *((struct PointerRNA **)_data);
	
	rna_GPencil_frame_remove(_self, reports, frame);
}

struct bGPDframe *GPencilFrames_copy(struct bGPDlayer *_self, struct bGPDframe *source)
{
	return rna_GPencil_frame_copy(_self, source);
}

void GPencilFrames_copy_call(bContext *C, ReportList *reports, PointerRNA *_ptr, ParameterList *_parms)
{
	struct bGPDlayer *_self;
	struct bGPDframe *source;
	struct bGPDframe *copy;
	char *_data, *_retdata;
	
	_self = (struct bGPDlayer *)_ptr->data;
	_data = (char *)_parms->data;
	source = *((struct bGPDframe **)_data);
	_data += 8;
	_retdata = _data;
	
	copy = rna_GPencil_frame_copy(_self, source);
	*((struct bGPDframe **)_retdata) = copy;
}

/* Repeated prototypes to detect errors */

struct bGPDframe *rna_GPencil_frame_new(struct bGPDlayer *_self, ReportList *reports, int frame_number);
void rna_GPencil_frame_remove(struct bGPDlayer *_self, ReportList *reports, struct PointerRNA *frame);
struct bGPDframe *rna_GPencil_frame_copy(struct bGPDlayer *_self, struct bGPDframe *source);

void GPencilFrame_clear(struct bGPDframe *_self)
{
	rna_GPencil_frame_clear(_self);
}

void GPencilFrame_clear_call(bContext *C, ReportList *reports, PointerRNA *_ptr, ParameterList *_parms)
{
	struct bGPDframe *_self;
	_self = (struct bGPDframe *)_ptr->data;
	
	rna_GPencil_frame_clear(_self);
}

/* Repeated prototypes to detect errors */

void rna_GPencil_frame_clear(struct bGPDframe *_self);

struct bGPDstroke *GPencilStrokes_new(struct bGPDframe *_self)
{
	return rna_GPencil_stroke_new(_self);
}

void GPencilStrokes_new_call(bContext *C, ReportList *reports, PointerRNA *_ptr, ParameterList *_parms)
{
	struct bGPDframe *_self;
	struct bGPDstroke *stroke;
	char *_data, *_retdata;
	
	_self = (struct bGPDframe *)_ptr->data;
	_data = (char *)_parms->data;
	_retdata = _data;
	
	stroke = rna_GPencil_stroke_new(_self);
	*((struct bGPDstroke **)_retdata) = stroke;
}

void GPencilStrokes_remove(struct bGPDframe *_self, ReportList *reports, struct PointerRNA *stroke)
{
	rna_GPencil_stroke_remove(_self, reports, stroke);
}

void GPencilStrokes_remove_call(bContext *C, ReportList *reports, PointerRNA *_ptr, ParameterList *_parms)
{
	struct bGPDframe *_self;
	struct PointerRNA *stroke;
	char *_data;
	
	_self = (struct bGPDframe *)_ptr->data;
	_data = (char *)_parms->data;
	stroke = *((struct PointerRNA **)_data);
	
	rna_GPencil_stroke_remove(_self, reports, stroke);
}

/* Repeated prototypes to detect errors */

struct bGPDstroke *rna_GPencil_stroke_new(struct bGPDframe *_self);
void rna_GPencil_stroke_remove(struct bGPDframe *_self, ReportList *reports, struct PointerRNA *stroke);


void GPencilStrokePoints_add(struct bGPDstroke *_self, int count)
{
	rna_GPencil_stroke_point_add(_self, count);
}

void GPencilStrokePoints_add_call(bContext *C, ReportList *reports, PointerRNA *_ptr, ParameterList *_parms)
{
	struct bGPDstroke *_self;
	int count;
	char *_data;
	
	_self = (struct bGPDstroke *)_ptr->data;
	_data = (char *)_parms->data;
	count = *((int *)_data);
	
	rna_GPencil_stroke_point_add(_self, count);
}

void GPencilStrokePoints_pop(struct bGPDstroke *_self, ReportList *reports, int index)
{
	rna_GPencil_stroke_point_pop(_self, reports, index);
}

void GPencilStrokePoints_pop_call(bContext *C, ReportList *reports, PointerRNA *_ptr, ParameterList *_parms)
{
	struct bGPDstroke *_self;
	int index;
	char *_data;
	
	_self = (struct bGPDstroke *)_ptr->data;
	_data = (char *)_parms->data;
	index = *((int *)_data);
	
	rna_GPencil_stroke_point_pop(_self, reports, index);
}

/* Repeated prototypes to detect errors */

void rna_GPencil_stroke_point_add(struct bGPDstroke *_self, int count);
void rna_GPencil_stroke_point_pop(struct bGPDstroke *_self, ReportList *reports, int index);


/* Grease Pencil */
CollectionPropertyRNA rna_GreasePencil_layers = {
	{(PropertyRNA *)&rna_GreasePencil_animation_data, NULL,
	-1, "layers", 0, "Layers",
	"",
	0, "*",
	PROP_COLLECTION, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, &RNA_GreasePencilLayers},
	GreasePencil_layers_begin, GreasePencil_layers_next, GreasePencil_layers_end, GreasePencil_layers_get, NULL, GreasePencil_layers_lookup_int, GreasePencil_layers_lookup_string, NULL, &RNA_GPencilLayer
};

PointerPropertyRNA rna_GreasePencil_animation_data = {
	{(PropertyRNA *)&rna_GreasePencil_use_stroke_edit_mode, (PropertyRNA *)&rna_GreasePencil_layers,
	-1, "animation_data", 8388608, "Animation Data",
	"Animation data for this data-block",
	0, "*",
	PROP_POINTER, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	GreasePencil_animation_data_get, NULL, NULL, NULL,&RNA_AnimData
};

BoolPropertyRNA rna_GreasePencil_use_stroke_edit_mode = {
	{(PropertyRNA *)&rna_GreasePencil_use_onion_skinning, (PropertyRNA *)&rna_GreasePencil_animation_data,
	-1, "use_stroke_edit_mode", 3, "Stroke Edit Mode",
	"Edit Grease Pencil strokes instead of viewport data",
	0, "*",
	PROP_BOOLEAN, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	rna_GPencil_editmode_update, 375324672, NULL, NULL,
	0, -1, NULL},
	GreasePencil_use_stroke_edit_mode_get, GreasePencil_use_stroke_edit_mode_set, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL
};

BoolPropertyRNA rna_GreasePencil_use_onion_skinning = {
	{NULL, (PropertyRNA *)&rna_GreasePencil_use_stroke_edit_mode,
	-1, "use_onion_skinning", 3, "Onion Skins",
	"Show ghosts of the frames before and after the current frame, toggle to enable on active layer or disable all",
	0, "*",
	PROP_BOOLEAN, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 375062528, NULL, NULL,
	0, -1, NULL},
	GreasePencil_use_onion_skinning_get, GreasePencil_use_onion_skinning_set, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL
};

FunctionRNA rna_GreasePencil_clear_func = {
	{NULL, NULL,
	NULL,
	{NULL, NULL}},
	"clear", 0, "Remove all the grease pencil data",
	GreasePencil_clear_call,
	NULL
};

StructRNA RNA_GreasePencil = {
	{(ContainerRNA *)&RNA_GreasePencilLayers, (ContainerRNA *)&RNA_ControlFluidSettings,
	NULL,
	{(PropertyRNA *)&rna_GreasePencil_layers, (PropertyRNA *)&rna_GreasePencil_use_onion_skinning}},
	"GreasePencil", NULL, NULL, 7, "Grease Pencil",
	"Freehand annotation sketchbook",
	"*", 197,
	(PropertyRNA *)&rna_ID_name, (PropertyRNA *)&rna_ID_rna_properties,
	&RNA_ID,
	NULL,
	rna_ID_refine,
	NULL,
	NULL,
	NULL,
	NULL,
	rna_ID_idprops,
	{(FunctionRNA *)&rna_GreasePencil_clear_func, (FunctionRNA *)&rna_GreasePencil_clear_func}
};

/* Grease Pencil Layers */
CollectionPropertyRNA rna_GreasePencilLayers_rna_properties = {
	{(PropertyRNA *)&rna_GreasePencilLayers_rna_type, NULL,
	-1, "rna_properties", 128, "Properties",
	"RNA property collection",
	0, "*",
	PROP_COLLECTION, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	GreasePencilLayers_rna_properties_begin, GreasePencilLayers_rna_properties_next, GreasePencilLayers_rna_properties_end, GreasePencilLayers_rna_properties_get, NULL, NULL, GreasePencilLayers_rna_properties_lookup_string, NULL, &RNA_Property
};

PointerPropertyRNA rna_GreasePencilLayers_rna_type = {
	{(PropertyRNA *)&rna_GreasePencilLayers_active, (PropertyRNA *)&rna_GreasePencilLayers_rna_properties,
	-1, "rna_type", 8912896, "RNA",
	"RNA type definition",
	0, "*",
	PROP_POINTER, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	GreasePencilLayers_rna_type_get, NULL, NULL, NULL,&RNA_Struct
};

PointerPropertyRNA rna_GreasePencilLayers_active = {
	{(PropertyRNA *)&rna_GreasePencilLayers_active_index, (PropertyRNA *)&rna_GreasePencilLayers_rna_type,
	-1, "active", 8388609, "Active Layer",
	"Active grease pencil layer",
	0, "*",
	PROP_POINTER, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	GreasePencilLayers_active_get, GreasePencilLayers_active_set, NULL, NULL,&RNA_GPencilLayer
};

IntPropertyRNA rna_GreasePencilLayers_active_index = {
	{NULL, (PropertyRNA *)&rna_GreasePencilLayers_active,
	-1, "active_index", 3, "Active Layer Index",
	"Index of active grease pencil layer",
	0, "*",
	PROP_INT, PROP_UNSIGNED | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	GreasePencilLayers_active_index_get, GreasePencilLayers_active_index_set, NULL, NULL, rna_GPencil_active_layer_index_range, NULL, NULL, NULL, NULL, NULL,
	0, 10000, 0, INT_MAX, 1, 0, NULL
};

StringPropertyRNA rna_GreasePencilLayers_new_name = {
	{(PropertyRNA *)&rna_GreasePencilLayers_new_set_active, NULL,
	-1, "name", 262149, "Name",
	"Name of the layer",
	0, "*",
	PROP_STRING, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	NULL, NULL, NULL, NULL, NULL, NULL, 64, "GPencilLayer"
};

BoolPropertyRNA rna_GreasePencilLayers_new_set_active = {
	{(PropertyRNA *)&rna_GreasePencilLayers_new_layer, (PropertyRNA *)&rna_GreasePencilLayers_new_name,
	-1, "set_active", 3, "Set Active",
	"Set the newly created layer to the active layer",
	0, "*",
	PROP_BOOLEAN, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL
};

PointerPropertyRNA rna_GreasePencilLayers_new_layer = {
	{NULL, (PropertyRNA *)&rna_GreasePencilLayers_new_set_active,
	-1, "layer", 8388616, "",
	"The newly created layer",
	0, "*",
	PROP_POINTER, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	NULL, NULL, NULL, NULL,&RNA_GPencilLayer
};

FunctionRNA rna_GreasePencilLayers_new_func = {
	{(FunctionRNA *)&rna_GreasePencilLayers_remove_func, NULL,
	NULL,
	{(PropertyRNA *)&rna_GreasePencilLayers_new_name, (PropertyRNA *)&rna_GreasePencilLayers_new_layer}},
	"new", 0, "Add a new grease pencil layer",
	GreasePencilLayers_new_call,
	(PropertyRNA *)&rna_GreasePencilLayers_new_layer
};

PointerPropertyRNA rna_GreasePencilLayers_remove_layer = {
	{NULL, NULL,
	-1, "layer", 264196, "",
	"The layer to remove",
	0, "*",
	PROP_POINTER, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	NULL, NULL, NULL, NULL,&RNA_GPencilLayer
};

FunctionRNA rna_GreasePencilLayers_remove_func = {
	{NULL, (FunctionRNA *)&rna_GreasePencilLayers_new_func,
	NULL,
	{(PropertyRNA *)&rna_GreasePencilLayers_remove_layer, (PropertyRNA *)&rna_GreasePencilLayers_remove_layer}},
	"remove", 16, "Remove a grease pencil layer",
	GreasePencilLayers_remove_call,
	NULL
};

StructRNA RNA_GreasePencilLayers = {
	{(ContainerRNA *)&RNA_GPencilLayer, (ContainerRNA *)&RNA_GreasePencil,
	NULL,
	{(PropertyRNA *)&rna_GreasePencilLayers_rna_properties, (PropertyRNA *)&rna_GreasePencilLayers_active_index}},
	"GreasePencilLayers", NULL, NULL, 4, "Grease Pencil Layers",
	"Collection of grease pencil layers",
	"*", 17,
	NULL, (PropertyRNA *)&rna_GreasePencilLayers_rna_properties,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	{(FunctionRNA *)&rna_GreasePencilLayers_new_func, (FunctionRNA *)&rna_GreasePencilLayers_remove_func}
};

/* Grease Pencil Layer */
CollectionPropertyRNA rna_GPencilLayer_rna_properties = {
	{(PropertyRNA *)&rna_GPencilLayer_rna_type, NULL,
	-1, "rna_properties", 128, "Properties",
	"RNA property collection",
	0, "*",
	PROP_COLLECTION, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	GPencilLayer_rna_properties_begin, GPencilLayer_rna_properties_next, GPencilLayer_rna_properties_end, GPencilLayer_rna_properties_get, NULL, NULL, GPencilLayer_rna_properties_lookup_string, NULL, &RNA_Property
};

PointerPropertyRNA rna_GPencilLayer_rna_type = {
	{(PropertyRNA *)&rna_GPencilLayer_info, (PropertyRNA *)&rna_GPencilLayer_rna_properties,
	-1, "rna_type", 8912896, "RNA",
	"RNA type definition",
	0, "*",
	PROP_POINTER, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	GPencilLayer_rna_type_get, NULL, NULL, NULL,&RNA_Struct
};

StringPropertyRNA rna_GPencilLayer_info = {
	{(PropertyRNA *)&rna_GPencilLayer_frames, (PropertyRNA *)&rna_GPencilLayer_rna_type,
	-1, "info", 262145, "Info",
	"Layer name",
	0, "*",
	PROP_STRING, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {128, 0, 0}, 0,
	NULL, 375062533, NULL, NULL,
	0, -1, NULL},
	GPencilLayer_info_get, GPencilLayer_info_length, GPencilLayer_info_set, NULL, NULL, NULL, 128, ""
};

CollectionPropertyRNA rna_GPencilLayer_frames = {
	{(PropertyRNA *)&rna_GPencilLayer_active_frame, (PropertyRNA *)&rna_GPencilLayer_info,
	-1, "frames", 0, "Frames",
	"Sketches for this layer on different frames",
	0, "*",
	PROP_COLLECTION, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, &RNA_GPencilFrames},
	GPencilLayer_frames_begin, GPencilLayer_frames_next, GPencilLayer_frames_end, GPencilLayer_frames_get, NULL, GPencilLayer_frames_lookup_int, NULL, NULL, &RNA_GPencilFrame
};

PointerPropertyRNA rna_GPencilLayer_active_frame = {
	{(PropertyRNA *)&rna_GPencilLayer_use_volumetric_strokes, (PropertyRNA *)&rna_GPencilLayer_frames,
	-1, "active_frame", 8388608, "Active Frame",
	"Frame currently being displayed for this layer",
	0, "*",
	PROP_POINTER, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 375062528, rna_GPencilLayer_active_frame_editable, NULL,
	0, -1, NULL},
	GPencilLayer_active_frame_get, NULL, NULL, NULL,&RNA_GPencilFrame
};

BoolPropertyRNA rna_GPencilLayer_use_volumetric_strokes = {
	{(PropertyRNA *)&rna_GPencilLayer_color, (PropertyRNA *)&rna_GPencilLayer_active_frame,
	-1, "use_volumetric_strokes", 3, "Volumetric Strokes",
	"Draw strokes as a series of circular blobs, resulting in a volumetric effect",
	0, "*",
	PROP_BOOLEAN, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	rna_GPencil_update, 375062528, NULL, NULL,
	0, -1, NULL},
	GPencilLayer_use_volumetric_strokes_get, GPencilLayer_use_volumetric_strokes_set, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL
};

static float rna_GPencilLayer_color_default[3] = {
	0.0f,
	0.0f,
	0.0f
};

FloatPropertyRNA rna_GPencilLayer_color = {
	{(PropertyRNA *)&rna_GPencilLayer_alpha, (PropertyRNA *)&rna_GPencilLayer_use_volumetric_strokes,
	-1, "color", 8195, "Color",
	"Color for all strokes in this layer",
	0, "*",
	PROP_FLOAT, PROP_COLOR_GAMMA | PROP_UNIT_NONE, NULL, 1, {3, 0, 0}, 3,
	rna_GPencil_update, 375062528, NULL, NULL,
	offsetof(bGPDlayer, color), 4, NULL},
	NULL, NULL, GPencilLayer_color_get, GPencilLayer_color_set, NULL, NULL, NULL, NULL, NULL, NULL, 0.0f, 1.0f, 0.0f, 1.0f, 10.0f, 3, 0.0f, rna_GPencilLayer_color_default
};

FloatPropertyRNA rna_GPencilLayer_alpha = {
	{(PropertyRNA *)&rna_GPencilLayer_fill_color, (PropertyRNA *)&rna_GPencilLayer_color,
	-1, "alpha", 8195, "Opacity",
	"Layer Opacity",
	0, "*",
	PROP_FLOAT, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	rna_GPencil_update, 375062528, NULL, NULL,
	offsetof(bGPDlayer, color[3]), 4, NULL},
	GPencilLayer_alpha_get, GPencilLayer_alpha_set, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.0f, 1.0f, 0.0f, 1.0f, 10.0f, 3, 0.0f, NULL
};

static float rna_GPencilLayer_fill_color_default[3] = {
	0.0f,
	0.0f,
	0.0f
};

FloatPropertyRNA rna_GPencilLayer_fill_color = {
	{(PropertyRNA *)&rna_GPencilLayer_fill_alpha, (PropertyRNA *)&rna_GPencilLayer_alpha,
	-1, "fill_color", 8195, "Fill Color",
	"Color for filling region bounded by each stroke",
	0, "*",
	PROP_FLOAT, PROP_COLOR_GAMMA | PROP_UNIT_NONE, NULL, 1, {3, 0, 0}, 3,
	rna_GPencil_update, 375062528, NULL, NULL,
	offsetof(bGPDlayer, fill), 4, NULL},
	NULL, NULL, GPencilLayer_fill_color_get, GPencilLayer_fill_color_set, NULL, NULL, NULL, NULL, NULL, NULL, 0.0f, 1.0f, 0.0f, 1.0f, 10.0f, 3, 0.0f, rna_GPencilLayer_fill_color_default
};

FloatPropertyRNA rna_GPencilLayer_fill_alpha = {
	{(PropertyRNA *)&rna_GPencilLayer_line_width, (PropertyRNA *)&rna_GPencilLayer_fill_color,
	-1, "fill_alpha", 8195, "Fill Opacity",
	"Opacity for filling region bounded by each stroke",
	0, "*",
	PROP_FLOAT, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	rna_GPencil_update, 375062528, NULL, NULL,
	offsetof(bGPDlayer, fill[3]), 4, NULL},
	GPencilLayer_fill_alpha_get, GPencilLayer_fill_alpha_set, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.0f, 1.0f, 0.0f, 1.0f, 10.0f, 3, 0.0f, NULL
};

IntPropertyRNA rna_GPencilLayer_line_width = {
	{(PropertyRNA *)&rna_GPencilLayer_use_onion_skinning, (PropertyRNA *)&rna_GPencilLayer_fill_alpha,
	-1, "line_width", 8195, "Thickness",
	"Thickness of strokes (in pixels)",
	0, "*",
	PROP_INT, PROP_PIXEL | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	rna_GPencil_update, 375062528, NULL, NULL,
	offsetof(bGPDlayer, thickness), 1, NULL},
	GPencilLayer_line_width_get, GPencilLayer_line_width_set, NULL, NULL, rna_GPencilLayer_line_width_range, NULL, NULL, NULL, NULL, NULL,
	-32768, 32767, -32768, 32767, 1, 0, NULL
};

BoolPropertyRNA rna_GPencilLayer_use_onion_skinning = {
	{(PropertyRNA *)&rna_GPencilLayer_ghost_before_range, (PropertyRNA *)&rna_GPencilLayer_line_width,
	-1, "use_onion_skinning", 3, "Onion Skinning",
	"Ghost frames on either side of frame",
	0, "*",
	PROP_BOOLEAN, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	rna_GPencil_onion_skinning_update, 375062528, NULL, NULL,
	0, -1, NULL},
	GPencilLayer_use_onion_skinning_get, GPencilLayer_use_onion_skinning_set, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL
};

IntPropertyRNA rna_GPencilLayer_ghost_before_range = {
	{(PropertyRNA *)&rna_GPencilLayer_ghost_after_range, (PropertyRNA *)&rna_GPencilLayer_use_onion_skinning,
	-1, "ghost_before_range", 8195, "Frames Before",
	"Maximum number of frames to show before current frame (0 = show only the previous sketch)",
	0, "*",
	PROP_INT, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	rna_GPencil_update, 375062528, NULL, NULL,
	offsetof(bGPDlayer, gstep), 1, NULL},
	GPencilLayer_ghost_before_range_get, GPencilLayer_ghost_before_range_set, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
	0, 120, 0, 120, 1, 0, NULL
};

IntPropertyRNA rna_GPencilLayer_ghost_after_range = {
	{(PropertyRNA *)&rna_GPencilLayer_use_ghost_custom_colors, (PropertyRNA *)&rna_GPencilLayer_ghost_before_range,
	-1, "ghost_after_range", 8195, "Frames After",
	"Maximum number of frames to show after current frame (0 = show only the next sketch)",
	0, "*",
	PROP_INT, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	rna_GPencil_update, 375062528, NULL, NULL,
	offsetof(bGPDlayer, gstep_next), 1, NULL},
	GPencilLayer_ghost_after_range_get, GPencilLayer_ghost_after_range_set, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
	0, 120, 0, 120, 1, 0, NULL
};

BoolPropertyRNA rna_GPencilLayer_use_ghost_custom_colors = {
	{(PropertyRNA *)&rna_GPencilLayer_before_color, (PropertyRNA *)&rna_GPencilLayer_ghost_after_range,
	-1, "use_ghost_custom_colors", 3, "Use Custom Ghost Colors",
	"Use custom colors for ghost frames",
	0, "*",
	PROP_BOOLEAN, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	rna_GPencil_update, 375062528, NULL, NULL,
	0, -1, NULL},
	GPencilLayer_use_ghost_custom_colors_get, GPencilLayer_use_ghost_custom_colors_set, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL
};

static float rna_GPencilLayer_before_color_default[3] = {
	0.0f,
	0.0f,
	0.0f
};

FloatPropertyRNA rna_GPencilLayer_before_color = {
	{(PropertyRNA *)&rna_GPencilLayer_after_color, (PropertyRNA *)&rna_GPencilLayer_use_ghost_custom_colors,
	-1, "before_color", 8195, "Before Color",
	"Base color for ghosts before the active frame",
	0, "*",
	PROP_FLOAT, PROP_COLOR_GAMMA | PROP_UNIT_NONE, NULL, 1, {3, 0, 0}, 3,
	rna_GPencil_update, 375062528, NULL, NULL,
	offsetof(bGPDlayer, gcolor_prev), 4, NULL},
	NULL, NULL, GPencilLayer_before_color_get, GPencilLayer_before_color_set, NULL, NULL, NULL, NULL, NULL, NULL, 0.0f, 1.0f, 0.0f, 1.0f, 10.0f, 3, 0.0f, rna_GPencilLayer_before_color_default
};

static float rna_GPencilLayer_after_color_default[3] = {
	0.0f,
	0.0f,
	0.0f
};

FloatPropertyRNA rna_GPencilLayer_after_color = {
	{(PropertyRNA *)&rna_GPencilLayer_hide, (PropertyRNA *)&rna_GPencilLayer_before_color,
	-1, "after_color", 8195, "After Color",
	"Base color for ghosts after the active frame",
	0, "*",
	PROP_FLOAT, PROP_COLOR_GAMMA | PROP_UNIT_NONE, NULL, 1, {3, 0, 0}, 3,
	rna_GPencil_update, 375062528, NULL, NULL,
	offsetof(bGPDlayer, gcolor_next), 4, NULL},
	NULL, NULL, GPencilLayer_after_color_get, GPencilLayer_after_color_set, NULL, NULL, NULL, NULL, NULL, NULL, 0.0f, 1.0f, 0.0f, 1.0f, 10.0f, 3, 0.0f, rna_GPencilLayer_after_color_default
};

BoolPropertyRNA rna_GPencilLayer_hide = {
	{(PropertyRNA *)&rna_GPencilLayer_lock, (PropertyRNA *)&rna_GPencilLayer_after_color,
	-1, "hide", 4099, "Hide",
	"Set layer Visibility",
	253, "*",
	PROP_BOOLEAN, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	rna_GPencil_update, 375062528, NULL, NULL,
	0, -1, NULL},
	GPencilLayer_hide_get, GPencilLayer_hide_set, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL
};

BoolPropertyRNA rna_GPencilLayer_lock = {
	{(PropertyRNA *)&rna_GPencilLayer_lock_frame, (PropertyRNA *)&rna_GPencilLayer_hide,
	-1, "lock", 4099, "Locked",
	"Protect layer from further editing and/or frame changes",
	40, "*",
	PROP_BOOLEAN, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	rna_GPencil_update, 375062528, NULL, NULL,
	0, -1, NULL},
	GPencilLayer_lock_get, GPencilLayer_lock_set, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL
};

BoolPropertyRNA rna_GPencilLayer_lock_frame = {
	{(PropertyRNA *)&rna_GPencilLayer_select, (PropertyRNA *)&rna_GPencilLayer_lock,
	-1, "lock_frame", 4099, "Frame Locked",
	"Lock current frame displayed by layer",
	40, "*",
	PROP_BOOLEAN, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	rna_GPencil_update, 375062528, NULL, NULL,
	0, -1, NULL},
	GPencilLayer_lock_frame_get, GPencilLayer_lock_frame_set, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL
};

BoolPropertyRNA rna_GPencilLayer_select = {
	{(PropertyRNA *)&rna_GPencilLayer_show_points, (PropertyRNA *)&rna_GPencilLayer_lock_frame,
	-1, "select", 3, "Select",
	"Layer is selected for editing in the Dope Sheet",
	0, "*",
	PROP_BOOLEAN, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	rna_GPencil_update, 375062528, NULL, NULL,
	0, -1, NULL},
	GPencilLayer_select_get, GPencilLayer_select_set, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL
};

BoolPropertyRNA rna_GPencilLayer_show_points = {
	{(PropertyRNA *)&rna_GPencilLayer_show_x_ray, (PropertyRNA *)&rna_GPencilLayer_select,
	-1, "show_points", 3, "Show Points",
	"Draw the points which make up the strokes (for debugging purposes)",
	0, "*",
	PROP_BOOLEAN, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	rna_GPencil_update, 375062528, NULL, NULL,
	0, -1, NULL},
	GPencilLayer_show_points_get, GPencilLayer_show_points_set, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL
};

BoolPropertyRNA rna_GPencilLayer_show_x_ray = {
	{(PropertyRNA *)&rna_GPencilLayer_is_stroke_visible, (PropertyRNA *)&rna_GPencilLayer_show_points,
	-1, "show_x_ray", 3, "X Ray",
	"Make the layer draw in front of objects",
	0, "*",
	PROP_BOOLEAN, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	rna_GPencil_update, 375062528, NULL, NULL,
	0, -1, NULL},
	GPencilLayer_show_x_ray_get, GPencilLayer_show_x_ray_set, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL
};

BoolPropertyRNA rna_GPencilLayer_is_stroke_visible = {
	{(PropertyRNA *)&rna_GPencilLayer_is_fill_visible, (PropertyRNA *)&rna_GPencilLayer_show_x_ray,
	-1, "is_stroke_visible", 2, "Is Stroke Visible",
	"True when opacity of stroke is set high enough to be visible",
	0, "*",
	PROP_BOOLEAN, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	GPencilLayer_is_stroke_visible_get, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL
};

BoolPropertyRNA rna_GPencilLayer_is_fill_visible = {
	{NULL, (PropertyRNA *)&rna_GPencilLayer_is_stroke_visible,
	-1, "is_fill_visible", 2, "Is Fill Visible",
	"True when opacity of fill is set high enough to be visible",
	0, "*",
	PROP_BOOLEAN, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	GPencilLayer_is_fill_visible_get, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL
};

FunctionRNA rna_GPencilLayer_clear_func = {
	{NULL, NULL,
	NULL,
	{NULL, NULL}},
	"clear", 0, "Remove all the grease pencil layer data",
	GPencilLayer_clear_call,
	NULL
};

StructRNA RNA_GPencilLayer = {
	{(ContainerRNA *)&RNA_GPencilFrames, (ContainerRNA *)&RNA_GreasePencilLayers,
	NULL,
	{(PropertyRNA *)&rna_GPencilLayer_rna_properties, (PropertyRNA *)&rna_GPencilLayer_is_fill_visible}},
	"GPencilLayer", NULL, NULL, 4, "Grease Pencil Layer",
	"Collection of related sketches",
	"*", 17,
	(PropertyRNA *)&rna_GPencilLayer_info, (PropertyRNA *)&rna_GPencilLayer_rna_properties,
	NULL,
	NULL,
	NULL,
	rna_GPencilLayer_path,
	NULL,
	NULL,
	NULL,
	NULL,
	{(FunctionRNA *)&rna_GPencilLayer_clear_func, (FunctionRNA *)&rna_GPencilLayer_clear_func}
};

/* Grease Pencil Frames */
CollectionPropertyRNA rna_GPencilFrames_rna_properties = {
	{(PropertyRNA *)&rna_GPencilFrames_rna_type, NULL,
	-1, "rna_properties", 128, "Properties",
	"RNA property collection",
	0, "*",
	PROP_COLLECTION, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	GPencilFrames_rna_properties_begin, GPencilFrames_rna_properties_next, GPencilFrames_rna_properties_end, GPencilFrames_rna_properties_get, NULL, NULL, GPencilFrames_rna_properties_lookup_string, NULL, &RNA_Property
};

PointerPropertyRNA rna_GPencilFrames_rna_type = {
	{NULL, (PropertyRNA *)&rna_GPencilFrames_rna_properties,
	-1, "rna_type", 8912896, "RNA",
	"RNA type definition",
	0, "*",
	PROP_POINTER, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	GPencilFrames_rna_type_get, NULL, NULL, NULL,&RNA_Struct
};

IntPropertyRNA rna_GPencilFrames_new_frame_number = {
	{(PropertyRNA *)&rna_GPencilFrames_new_frame, NULL,
	-1, "frame_number", 7, "Frame Number",
	"The frame on which this sketch appears",
	0, "*",
	PROP_INT, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
	-300000, 300000, -300000, 300000, 1, 1, NULL
};

PointerPropertyRNA rna_GPencilFrames_new_frame = {
	{NULL, (PropertyRNA *)&rna_GPencilFrames_new_frame_number,
	-1, "frame", 8388616, "",
	"The newly created frame",
	0, "*",
	PROP_POINTER, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	NULL, NULL, NULL, NULL,&RNA_GPencilFrame
};

FunctionRNA rna_GPencilFrames_new_func = {
	{(FunctionRNA *)&rna_GPencilFrames_remove_func, NULL,
	NULL,
	{(PropertyRNA *)&rna_GPencilFrames_new_frame_number, (PropertyRNA *)&rna_GPencilFrames_new_frame}},
	"new", 16, "Add a new grease pencil frame",
	GPencilFrames_new_call,
	(PropertyRNA *)&rna_GPencilFrames_new_frame
};

PointerPropertyRNA rna_GPencilFrames_remove_frame = {
	{NULL, NULL,
	-1, "frame", 264196, "Frame",
	"The frame to remove",
	0, "*",
	PROP_POINTER, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	NULL, NULL, NULL, NULL,&RNA_GPencilFrame
};

FunctionRNA rna_GPencilFrames_remove_func = {
	{(FunctionRNA *)&rna_GPencilFrames_copy_func, (FunctionRNA *)&rna_GPencilFrames_new_func,
	NULL,
	{(PropertyRNA *)&rna_GPencilFrames_remove_frame, (PropertyRNA *)&rna_GPencilFrames_remove_frame}},
	"remove", 16, "Remove a grease pencil frame",
	GPencilFrames_remove_call,
	NULL
};

PointerPropertyRNA rna_GPencilFrames_copy_source = {
	{(PropertyRNA *)&rna_GPencilFrames_copy_copy, NULL,
	-1, "source", 8650756, "Source",
	"The source frame",
	0, "*",
	PROP_POINTER, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	NULL, NULL, NULL, NULL,&RNA_GPencilFrame
};

PointerPropertyRNA rna_GPencilFrames_copy_copy = {
	{NULL, (PropertyRNA *)&rna_GPencilFrames_copy_source,
	-1, "copy", 8388616, "",
	"The newly copied frame",
	0, "*",
	PROP_POINTER, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	NULL, NULL, NULL, NULL,&RNA_GPencilFrame
};

FunctionRNA rna_GPencilFrames_copy_func = {
	{NULL, (FunctionRNA *)&rna_GPencilFrames_remove_func,
	NULL,
	{(PropertyRNA *)&rna_GPencilFrames_copy_source, (PropertyRNA *)&rna_GPencilFrames_copy_copy}},
	"copy", 0, "Copy a grease pencil frame",
	GPencilFrames_copy_call,
	(PropertyRNA *)&rna_GPencilFrames_copy_copy
};

StructRNA RNA_GPencilFrames = {
	{(ContainerRNA *)&RNA_GPencilFrame, (ContainerRNA *)&RNA_GPencilLayer,
	NULL,
	{(PropertyRNA *)&rna_GPencilFrames_rna_properties, (PropertyRNA *)&rna_GPencilFrames_rna_type}},
	"GPencilFrames", NULL, NULL, 4, "Grease Pencil Frames",
	"Collection of grease pencil frames",
	"*", 17,
	NULL, (PropertyRNA *)&rna_GPencilFrames_rna_properties,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	{(FunctionRNA *)&rna_GPencilFrames_new_func, (FunctionRNA *)&rna_GPencilFrames_copy_func}
};

/* Grease Pencil Frame */
CollectionPropertyRNA rna_GPencilFrame_rna_properties = {
	{(PropertyRNA *)&rna_GPencilFrame_rna_type, NULL,
	-1, "rna_properties", 128, "Properties",
	"RNA property collection",
	0, "*",
	PROP_COLLECTION, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	GPencilFrame_rna_properties_begin, GPencilFrame_rna_properties_next, GPencilFrame_rna_properties_end, GPencilFrame_rna_properties_get, NULL, NULL, GPencilFrame_rna_properties_lookup_string, NULL, &RNA_Property
};

PointerPropertyRNA rna_GPencilFrame_rna_type = {
	{(PropertyRNA *)&rna_GPencilFrame_strokes, (PropertyRNA *)&rna_GPencilFrame_rna_properties,
	-1, "rna_type", 8912896, "RNA",
	"RNA type definition",
	0, "*",
	PROP_POINTER, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	GPencilFrame_rna_type_get, NULL, NULL, NULL,&RNA_Struct
};

CollectionPropertyRNA rna_GPencilFrame_strokes = {
	{(PropertyRNA *)&rna_GPencilFrame_frame_number, (PropertyRNA *)&rna_GPencilFrame_rna_type,
	-1, "strokes", 0, "Strokes",
	"Freehand curves defining the sketch on this frame",
	0, "*",
	PROP_COLLECTION, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, &RNA_GPencilStrokes},
	GPencilFrame_strokes_begin, GPencilFrame_strokes_next, GPencilFrame_strokes_end, GPencilFrame_strokes_get, NULL, GPencilFrame_strokes_lookup_int, NULL, NULL, &RNA_GPencilStroke
};

IntPropertyRNA rna_GPencilFrame_frame_number = {
	{(PropertyRNA *)&rna_GPencilFrame_is_edited, (PropertyRNA *)&rna_GPencilFrame_strokes,
	-1, "frame_number", 8195, "Frame Number",
	"The frame on which this sketch appears",
	0, "*",
	PROP_INT, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	offsetof(bGPDframe, framenum), 0, NULL},
	GPencilFrame_frame_number_get, GPencilFrame_frame_number_set, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
	-300000, 300000, -300000, 300000, 1, 0, NULL
};

BoolPropertyRNA rna_GPencilFrame_is_edited = {
	{(PropertyRNA *)&rna_GPencilFrame_select, (PropertyRNA *)&rna_GPencilFrame_frame_number,
	-1, "is_edited", 3, "Paint Lock",
	"Frame is being edited (painted on)",
	0, "*",
	PROP_BOOLEAN, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	GPencilFrame_is_edited_get, GPencilFrame_is_edited_set, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL
};

BoolPropertyRNA rna_GPencilFrame_select = {
	{NULL, (PropertyRNA *)&rna_GPencilFrame_is_edited,
	-1, "select", 3, "Select",
	"Frame is selected for editing in the Dope Sheet",
	0, "*",
	PROP_BOOLEAN, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	GPencilFrame_select_get, GPencilFrame_select_set, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL
};

FunctionRNA rna_GPencilFrame_clear_func = {
	{NULL, NULL,
	NULL,
	{NULL, NULL}},
	"clear", 0, "Remove all the grease pencil frame data",
	GPencilFrame_clear_call,
	NULL
};

StructRNA RNA_GPencilFrame = {
	{(ContainerRNA *)&RNA_GPencilStrokes, (ContainerRNA *)&RNA_GPencilFrames,
	NULL,
	{(PropertyRNA *)&rna_GPencilFrame_rna_properties, (PropertyRNA *)&rna_GPencilFrame_select}},
	"GPencilFrame", NULL, NULL, 4, "Grease Pencil Frame",
	"Collection of related sketches on a particular frame",
	"*", 17,
	NULL, (PropertyRNA *)&rna_GPencilFrame_rna_properties,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	{(FunctionRNA *)&rna_GPencilFrame_clear_func, (FunctionRNA *)&rna_GPencilFrame_clear_func}
};

/* Grease Pencil Frames */
CollectionPropertyRNA rna_GPencilStrokes_rna_properties = {
	{(PropertyRNA *)&rna_GPencilStrokes_rna_type, NULL,
	-1, "rna_properties", 128, "Properties",
	"RNA property collection",
	0, "*",
	PROP_COLLECTION, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	GPencilStrokes_rna_properties_begin, GPencilStrokes_rna_properties_next, GPencilStrokes_rna_properties_end, GPencilStrokes_rna_properties_get, NULL, NULL, GPencilStrokes_rna_properties_lookup_string, NULL, &RNA_Property
};

PointerPropertyRNA rna_GPencilStrokes_rna_type = {
	{NULL, (PropertyRNA *)&rna_GPencilStrokes_rna_properties,
	-1, "rna_type", 8912896, "RNA",
	"RNA type definition",
	0, "*",
	PROP_POINTER, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	GPencilStrokes_rna_type_get, NULL, NULL, NULL,&RNA_Struct
};

PointerPropertyRNA rna_GPencilStrokes_new_stroke = {
	{NULL, NULL,
	-1, "stroke", 8388616, "",
	"The newly created stroke",
	0, "*",
	PROP_POINTER, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	NULL, NULL, NULL, NULL,&RNA_GPencilStroke
};

FunctionRNA rna_GPencilStrokes_new_func = {
	{(FunctionRNA *)&rna_GPencilStrokes_remove_func, NULL,
	NULL,
	{(PropertyRNA *)&rna_GPencilStrokes_new_stroke, (PropertyRNA *)&rna_GPencilStrokes_new_stroke}},
	"new", 0, "Add a new grease pencil stroke",
	GPencilStrokes_new_call,
	(PropertyRNA *)&rna_GPencilStrokes_new_stroke
};

PointerPropertyRNA rna_GPencilStrokes_remove_stroke = {
	{NULL, NULL,
	-1, "stroke", 264196, "Stroke",
	"The stroke to remove",
	0, "*",
	PROP_POINTER, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	NULL, NULL, NULL, NULL,&RNA_GPencilStroke
};

FunctionRNA rna_GPencilStrokes_remove_func = {
	{NULL, (FunctionRNA *)&rna_GPencilStrokes_new_func,
	NULL,
	{(PropertyRNA *)&rna_GPencilStrokes_remove_stroke, (PropertyRNA *)&rna_GPencilStrokes_remove_stroke}},
	"remove", 16, "Remove a grease pencil stroke",
	GPencilStrokes_remove_call,
	NULL
};

StructRNA RNA_GPencilStrokes = {
	{(ContainerRNA *)&RNA_GPencilStroke, (ContainerRNA *)&RNA_GPencilFrame,
	NULL,
	{(PropertyRNA *)&rna_GPencilStrokes_rna_properties, (PropertyRNA *)&rna_GPencilStrokes_rna_type}},
	"GPencilStrokes", NULL, NULL, 4, "Grease Pencil Frames",
	"Collection of grease pencil stroke",
	"*", 17,
	NULL, (PropertyRNA *)&rna_GPencilStrokes_rna_properties,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	{(FunctionRNA *)&rna_GPencilStrokes_new_func, (FunctionRNA *)&rna_GPencilStrokes_remove_func}
};

/* Grease Pencil Stroke */
CollectionPropertyRNA rna_GPencilStroke_rna_properties = {
	{(PropertyRNA *)&rna_GPencilStroke_rna_type, NULL,
	-1, "rna_properties", 128, "Properties",
	"RNA property collection",
	0, "*",
	PROP_COLLECTION, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	GPencilStroke_rna_properties_begin, GPencilStroke_rna_properties_next, GPencilStroke_rna_properties_end, GPencilStroke_rna_properties_get, NULL, NULL, GPencilStroke_rna_properties_lookup_string, NULL, &RNA_Property
};

PointerPropertyRNA rna_GPencilStroke_rna_type = {
	{(PropertyRNA *)&rna_GPencilStroke_points, (PropertyRNA *)&rna_GPencilStroke_rna_properties,
	-1, "rna_type", 8912896, "RNA",
	"RNA type definition",
	0, "*",
	PROP_POINTER, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	GPencilStroke_rna_type_get, NULL, NULL, NULL,&RNA_Struct
};

CollectionPropertyRNA rna_GPencilStroke_points = {
	{(PropertyRNA *)&rna_GPencilStroke_draw_mode, (PropertyRNA *)&rna_GPencilStroke_rna_type,
	-1, "points", 16384, "Stroke Points",
	"Stroke data points",
	0, "*",
	PROP_COLLECTION, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, &RNA_GPencilStrokePoints},
	GPencilStroke_points_begin, GPencilStroke_points_next, GPencilStroke_points_end, GPencilStroke_points_get, GPencilStroke_points_length, GPencilStroke_points_lookup_int, NULL, NULL, &RNA_GPencilStrokePoint
};

static EnumPropertyItem rna_GPencilStroke_draw_mode_items[5] = {
	{0, "SCREEN", 0, "Screen", "Stroke is in screen-space"},
	{1, "3DSPACE", 0, "3D Space", "Stroke is in 3D-space"},
	{2, "2DSPACE", 0, "2D Space", "Stroke is in 2D-space"},
	{4, "2DIMAGE", 0, "2D Image", "Stroke is in 2D-space (but with special \'image\' scaling)"},
	{0, NULL, 0, NULL, NULL}
};

EnumPropertyRNA rna_GPencilStroke_draw_mode = {
	{(PropertyRNA *)&rna_GPencilStroke_select, (PropertyRNA *)&rna_GPencilStroke_points,
	-1, "draw_mode", 3, "Draw Mode",
	"",
	0, "*",
	PROP_ENUM, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	rna_GPencil_update, 0, NULL, NULL,
	0, -1, NULL},
	GPencilStroke_draw_mode_get, GPencilStroke_draw_mode_set, NULL, NULL, NULL, NULL, rna_GPencilStroke_draw_mode_items, 4, 0
};

BoolPropertyRNA rna_GPencilStroke_select = {
	{NULL, (PropertyRNA *)&rna_GPencilStroke_draw_mode,
	-1, "select", 3, "Select",
	"Stroke is selected for viewport editing",
	0, "*",
	PROP_BOOLEAN, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	rna_GPencil_update, 0, NULL, NULL,
	0, -1, NULL},
	GPencilStroke_select_get, GPencilStroke_select_set, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL
};

StructRNA RNA_GPencilStroke = {
	{(ContainerRNA *)&RNA_GPencilStrokePoints, (ContainerRNA *)&RNA_GPencilStrokes,
	NULL,
	{(PropertyRNA *)&rna_GPencilStroke_rna_properties, (PropertyRNA *)&rna_GPencilStroke_select}},
	"GPencilStroke", NULL, NULL, 4, "Grease Pencil Stroke",
	"Freehand curve defining part of a sketch",
	"*", 17,
	NULL, (PropertyRNA *)&rna_GPencilStroke_rna_properties,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	{NULL, NULL}
};

/* Grease Pencil Stroke Points */
CollectionPropertyRNA rna_GPencilStrokePoints_rna_properties = {
	{(PropertyRNA *)&rna_GPencilStrokePoints_rna_type, NULL,
	-1, "rna_properties", 128, "Properties",
	"RNA property collection",
	0, "*",
	PROP_COLLECTION, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	GPencilStrokePoints_rna_properties_begin, GPencilStrokePoints_rna_properties_next, GPencilStrokePoints_rna_properties_end, GPencilStrokePoints_rna_properties_get, NULL, NULL, GPencilStrokePoints_rna_properties_lookup_string, NULL, &RNA_Property
};

PointerPropertyRNA rna_GPencilStrokePoints_rna_type = {
	{NULL, (PropertyRNA *)&rna_GPencilStrokePoints_rna_properties,
	-1, "rna_type", 8912896, "RNA",
	"RNA type definition",
	0, "*",
	PROP_POINTER, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	GPencilStrokePoints_rna_type_get, NULL, NULL, NULL,&RNA_Struct
};

IntPropertyRNA rna_GPencilStrokePoints_add_count = {
	{NULL, NULL,
	-1, "count", 3, "Number",
	"Number of points to add to the stroke",
	0, "*",
	PROP_INT, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
	0, INT_MAX, 0, INT_MAX, 1, 1, NULL
};

FunctionRNA rna_GPencilStrokePoints_add_func = {
	{(FunctionRNA *)&rna_GPencilStrokePoints_pop_func, NULL,
	NULL,
	{(PropertyRNA *)&rna_GPencilStrokePoints_add_count, (PropertyRNA *)&rna_GPencilStrokePoints_add_count}},
	"add", 0, "Add a new grease pencil stroke point",
	GPencilStrokePoints_add_call,
	NULL
};

IntPropertyRNA rna_GPencilStrokePoints_pop_index = {
	{NULL, NULL,
	-1, "index", 3, "Index",
	"point index",
	0, "*",
	PROP_INT, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
	INT_MIN, INT_MAX, INT_MIN, INT_MAX, 1, -1, NULL
};

FunctionRNA rna_GPencilStrokePoints_pop_func = {
	{NULL, (FunctionRNA *)&rna_GPencilStrokePoints_add_func,
	NULL,
	{(PropertyRNA *)&rna_GPencilStrokePoints_pop_index, (PropertyRNA *)&rna_GPencilStrokePoints_pop_index}},
	"pop", 16, "Remove a grease pencil stroke point",
	GPencilStrokePoints_pop_call,
	NULL
};

StructRNA RNA_GPencilStrokePoints = {
	{(ContainerRNA *)&RNA_GPencilStrokePoint, (ContainerRNA *)&RNA_GPencilStroke,
	NULL,
	{(PropertyRNA *)&rna_GPencilStrokePoints_rna_properties, (PropertyRNA *)&rna_GPencilStrokePoints_rna_type}},
	"GPencilStrokePoints", NULL, NULL, 4, "Grease Pencil Stroke Points",
	"Collection of grease pencil stroke points",
	"*", 17,
	NULL, (PropertyRNA *)&rna_GPencilStrokePoints_rna_properties,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	{(FunctionRNA *)&rna_GPencilStrokePoints_add_func, (FunctionRNA *)&rna_GPencilStrokePoints_pop_func}
};

/* Grease Pencil Stroke Point */
CollectionPropertyRNA rna_GPencilStrokePoint_rna_properties = {
	{(PropertyRNA *)&rna_GPencilStrokePoint_rna_type, NULL,
	-1, "rna_properties", 128, "Properties",
	"RNA property collection",
	0, "*",
	PROP_COLLECTION, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	GPencilStrokePoint_rna_properties_begin, GPencilStrokePoint_rna_properties_next, GPencilStrokePoint_rna_properties_end, GPencilStrokePoint_rna_properties_get, NULL, NULL, GPencilStrokePoint_rna_properties_lookup_string, NULL, &RNA_Property
};

PointerPropertyRNA rna_GPencilStrokePoint_rna_type = {
	{(PropertyRNA *)&rna_GPencilStrokePoint_co, (PropertyRNA *)&rna_GPencilStrokePoint_rna_properties,
	-1, "rna_type", 8912896, "RNA",
	"RNA type definition",
	0, "*",
	PROP_POINTER, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL,
	0, -1, NULL},
	GPencilStrokePoint_rna_type_get, NULL, NULL, NULL,&RNA_Struct
};

static float rna_GPencilStrokePoint_co_default[3] = {
	0.0f,
	0.0f,
	0.0f
};

FloatPropertyRNA rna_GPencilStrokePoint_co = {
	{(PropertyRNA *)&rna_GPencilStrokePoint_pressure, (PropertyRNA *)&rna_GPencilStrokePoint_rna_type,
	-1, "co", 8195, "Coordinates",
	"",
	0, "*",
	PROP_FLOAT, PROP_XYZ | PROP_UNIT_NONE, NULL, 1, {3, 0, 0}, 3,
	rna_GPencil_update, 375062528, NULL, NULL,
	offsetof(bGPDspoint, x), 4, NULL},
	NULL, NULL, GPencilStrokePoint_co_get, GPencilStrokePoint_co_set, NULL, NULL, NULL, NULL, NULL, NULL, -10000.0f, 10000.0f, -FLT_MAX, FLT_MAX, 10.0f, 3, 0.0f, rna_GPencilStrokePoint_co_default
};

FloatPropertyRNA rna_GPencilStrokePoint_pressure = {
	{(PropertyRNA *)&rna_GPencilStrokePoint_select, (PropertyRNA *)&rna_GPencilStrokePoint_co,
	-1, "pressure", 8195, "Pressure",
	"Pressure of tablet at point when drawing it",
	0, "*",
	PROP_FLOAT, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	rna_GPencil_update, 375062528, NULL, NULL,
	offsetof(bGPDspoint, pressure), 4, NULL},
	GPencilStrokePoint_pressure_get, GPencilStrokePoint_pressure_set, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.0f, 1.0f, 0.0f, 1.0f, 10.0f, 3, 0.0f, NULL
};

BoolPropertyRNA rna_GPencilStrokePoint_select = {
	{NULL, (PropertyRNA *)&rna_GPencilStrokePoint_pressure,
	-1, "select", 3, "Select",
	"Point is selected for viewport editing",
	0, "*",
	PROP_BOOLEAN, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	rna_GPencil_update, 375062528, NULL, NULL,
	0, -1, NULL},
	GPencilStrokePoint_select_get, GPencilStrokePoint_select_set, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL
};

StructRNA RNA_GPencilStrokePoint = {
	{(ContainerRNA *)&RNA_Group, (ContainerRNA *)&RNA_GPencilStrokePoints,
	NULL,
	{(PropertyRNA *)&rna_GPencilStrokePoint_rna_properties, (PropertyRNA *)&rna_GPencilStrokePoint_select}},
	"GPencilStrokePoint", NULL, NULL, 4, "Grease Pencil Stroke Point",
	"Data point for freehand stroke curve",
	"*", 17,
	NULL, (PropertyRNA *)&rna_GPencilStrokePoint_rna_properties,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	{NULL, NULL}
};

