# CMake generated Testfile for 
# Source directory: D:/blenderDev/blender/tests/python
# Build directory: D:/blenderDev/product/tests/python
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(script_load_keymap "D:/blenderDev/product/bin/blender" "--background" "-noaudio" "--factory-startup" "--env-system-scripts" "D:/blenderDev/blender/release/scripts" "--python" "D:/blenderDev/blender/tests/python/bl_keymap_completeness.py")
ADD_TEST(script_load_addons "D:/blenderDev/product/bin/blender" "--background" "-noaudio" "--factory-startup" "--env-system-scripts" "D:/blenderDev/blender/release/scripts" "--python" "D:/blenderDev/blender/tests/python/bl_load_addons.py")
ADD_TEST(script_load_modules "D:/blenderDev/product/bin/blender" "--background" "-noaudio" "--factory-startup" "--env-system-scripts" "D:/blenderDev/blender/release/scripts" "--python" "D:/blenderDev/blender/tests/python/bl_load_py_modules.py")
ADD_TEST(script_pyapi_bpy_path "D:/blenderDev/product/bin/blender" "--background" "-noaudio" "--factory-startup" "--env-system-scripts" "D:/blenderDev/blender/release/scripts" "--python" "D:/blenderDev/blender/tests/python/bl_pyapi_bpy_path.py")
ADD_TEST(script_pyapi_bpy_utils_units "D:/blenderDev/product/bin/blender" "--background" "-noaudio" "--factory-startup" "--env-system-scripts" "D:/blenderDev/blender/release/scripts" "--python" "D:/blenderDev/blender/tests/python/bl_pyapi_bpy_utils_units.py")
ADD_TEST(script_pyapi_mathutils "D:/blenderDev/product/bin/blender" "--background" "-noaudio" "--factory-startup" "--env-system-scripts" "D:/blenderDev/blender/release/scripts" "--python" "D:/blenderDev/blender/tests/python/bl_pyapi_mathutils.py")
ADD_TEST(bevel "D:/blenderDev/product/bin/blender" "--background" "-noaudio" "--factory-startup" "--env-system-scripts" "D:/blenderDev/blender/release/scripts" "D:/blenderDev/blender/../lib/tests/modeling/bevel_regression.blend" "--python-text" "run_tests")
ADD_TEST(export_obj_cube "D:/blenderDev/product/bin/blender" "--background" "-noaudio" "--factory-startup" "--env-system-scripts" "D:/blenderDev/blender/release/scripts" "D:/blenderDev/blender/../lib/tests/io_tests/blend_geometry/all_quads.blend" "--python" "D:/blenderDev/blender/tests/python/bl_test.py" "--" "--run={'FINISHED'}&bpy.ops.export_scene.obj(filepath='D:/blenderDev/product/tests/export_obj_cube.obj',use_selection=False)" "--md5_source=D:/blenderDev/product/tests/export_obj_cube.obj" "--md5_source=D:/blenderDev/product/tests/export_obj_cube.mtl" "--md5=e776c6f8e9e0afba346e85bcd10b8e99" "--md5_method=FILE")
ADD_TEST(export_obj_nurbs "D:/blenderDev/product/bin/blender" "--background" "-noaudio" "--factory-startup" "--env-system-scripts" "D:/blenderDev/blender/release/scripts" "D:/blenderDev/blender/../lib/tests/io_tests/blend_geometry/nurbs.blend" "--python" "D:/blenderDev/blender/tests/python/bl_test.py" "--" "--run={'FINISHED'}&bpy.ops.export_scene.obj(filepath='D:/blenderDev/product/tests/export_obj_nurbs.obj',use_selection=False,use_nurbs=True)" "--md5_source=D:/blenderDev/product/tests/export_obj_nurbs.obj" "--md5_source=D:/blenderDev/product/tests/export_obj_nurbs.mtl" "--md5=a733ae4fa4a591ea9b0912da3af042de" "--md5_method=FILE")
ADD_TEST(import_ply_cube "D:/blenderDev/product/bin/blender" "--background" "-noaudio" "--factory-startup" "--env-system-scripts" "D:/blenderDev/blender/release/scripts" "--python" "D:/blenderDev/blender/tests/python/bl_test.py" "--" "--run={'FINISHED'}&bpy.ops.import_mesh.ply(filepath='D:/blenderDev/blender/../lib/tests/io_tests/ply/cube_ascii.ply')" "--md5=527134343c27fc0ea73115b85fbfd3ac" "--md5_method=SCENE" "--write-blend=D:/blenderDev/product/tests/import_ply_cube.blend")
ADD_TEST(import_ply_bunny "D:/blenderDev/product/bin/blender" "--background" "-noaudio" "--factory-startup" "--env-system-scripts" "D:/blenderDev/blender/release/scripts" "--python" "D:/blenderDev/blender/tests/python/bl_test.py" "--" "--run={'FINISHED'}&bpy.ops.import_mesh.ply(filepath='D:/blenderDev/blender/../lib/tests/io_tests/ply/bunny2.ply')" "--md5=6ea5b8533400a17accf928b8fd024eaa" "--md5_method=SCENE" "--write-blend=D:/blenderDev/product/tests/import_ply_bunny.blend")
ADD_TEST(import_ply_small_holes "D:/blenderDev/product/bin/blender" "--background" "-noaudio" "--factory-startup" "--env-system-scripts" "D:/blenderDev/blender/release/scripts" "--python" "D:/blenderDev/blender/tests/python/bl_test.py" "--" "--run={'FINISHED'}&bpy.ops.import_mesh.ply(filepath='D:/blenderDev/blender/../lib/tests/io_tests/ply/many_small_holes.ply')" "--md5=c3093e26ecae5b6d59fbbcf2a0d0b39f" "--md5_method=SCENE" "--write-blend=D:/blenderDev/product/tests/import_ply_small_holes.blend")
ADD_TEST(export_ply_vertices "D:/blenderDev/product/bin/blender" "--background" "-noaudio" "--factory-startup" "--env-system-scripts" "D:/blenderDev/blender/release/scripts" "D:/blenderDev/blender/../lib/tests/io_tests/blend_geometry/vertices.blend" "--python" "D:/blenderDev/blender/tests/python/bl_test.py" "--" "--run={'FINISHED'}&bpy.ops.export_mesh.ply(filepath='D:/blenderDev/product/tests/export_ply_vertices.ply')" "--md5_source=D:/blenderDev/product/tests/export_ply_vertices.ply" "--md5=37faba0aa2014451b27f951afa92f870" "--md5_method=FILE")
