# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


SET(CPACK_BINARY_BUNDLE "")
SET(CPACK_BINARY_CYGWIN "")
SET(CPACK_BINARY_DEB "")
SET(CPACK_BINARY_DRAGNDROP "")
SET(CPACK_BINARY_NSIS "ON")
SET(CPACK_BINARY_OSXX11 "")
SET(CPACK_BINARY_PACKAGEMAKER "")
SET(CPACK_BINARY_RPM "")
SET(CPACK_BINARY_STGZ "")
SET(CPACK_BINARY_TBZ2 "")
SET(CPACK_BINARY_TGZ "")
SET(CPACK_BINARY_TZ "")
SET(CPACK_BINARY_WIX "OFF")
SET(CPACK_BINARY_ZIP "OFF")
SET(CPACK_CMAKE_GENERATOR "Visual Studio 12 Win64")
SET(CPACK_COMPONENTS_ALL "Blender;Unspecified")
SET(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
SET(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
SET(CPACK_DATE "")
SET(CPACK_GENERATOR "NSIS")
SET(CPACK_INSTALL_CMAKE_PROJECTS "D:/blenderDev/product;Blender;ALL;/")
SET(CPACK_INSTALL_PREFIX "C:/Program Files/")
SET(CPACK_MODULE_PATH "D:/blenderDev/blender/build_files/cmake/Modules")
SET(CPACK_NSIS_COMPRESSOR "/SOLID lzma")
SET(CPACK_NSIS_DISPLAY_NAME "Blender Foundation/Blender")
SET(CPACK_NSIS_INSTALLER_ICON_CODE "")
SET(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
SET(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
SET(CPACK_NSIS_MUI_ICON "D:/blenderDev/blender/release/windows/icons/winblender.ico")
SET(CPACK_NSIS_PACKAGE_NAME "Blender Foundation/Blender")
SET(CPACK_OUTPUT_CONFIG_FILE "D:/blenderDev/product/CPackConfig.cmake")
SET(CPACK_PACKAGE_CONTACT "foundation@blender.org")
SET(CPACK_PACKAGE_DEFAULT_LOCATION "/")
SET(CPACK_PACKAGE_DESCRIPTION "Blender is a very fast and versatile 3D modeller/renderer.")
SET(CPACK_PACKAGE_DESCRIPTION_FILE "D:/luxrender/windows_deps/bin/CMake/share/cmake-2.8/Templates/CPack.GenericDescription.txt")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Blender built using CMake")
SET(CPACK_PACKAGE_EXECUTABLES "blender;blender")
SET(CPACK_PACKAGE_FILE_NAME "blender-2.77.0-git.unknown-AMD64")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "Blender Foundation/Blender")
SET(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "Blender Foundation/Blender")
SET(CPACK_PACKAGE_NAME "Blender")
SET(CPACK_PACKAGE_RELOCATABLE "true")
SET(CPACK_PACKAGE_VENDOR "Blender Foundation")
SET(CPACK_PACKAGE_VERSION "2.77.0")
SET(CPACK_PACKAGE_VERSION_MAJOR "2")
SET(CPACK_PACKAGE_VERSION_MINOR "77")
SET(CPACK_PACKAGE_VERSION_PATCH "0")
SET(CPACK_RESOURCE_FILE_LICENSE "D:/blenderDev/blender/release/text/GPL-license.txt")
SET(CPACK_RESOURCE_FILE_README "D:/luxrender/windows_deps/bin/CMake/share/cmake-2.8/Templates/CPack.GenericDescription.txt")
SET(CPACK_RESOURCE_FILE_WELCOME "D:/luxrender/windows_deps/bin/CMake/share/cmake-2.8/Templates/CPack.GenericWelcome.txt")
SET(CPACK_SET_DESTDIR "OFF")
SET(CPACK_SOURCE_CYGWIN "")
SET(CPACK_SOURCE_GENERATOR "ZIP")
SET(CPACK_SOURCE_OUTPUT_CONFIG_FILE "D:/blenderDev/product/CPackSourceConfig.cmake")
SET(CPACK_SOURCE_TBZ2 "")
SET(CPACK_SOURCE_TGZ "")
SET(CPACK_SOURCE_TZ "")
SET(CPACK_SOURCE_ZIP "ON")
SET(CPACK_SYSTEM_NAME "Windows")
SET(CPACK_TOPLEVEL_TAG "Windows")
SET(CPACK_WIX_LIGHT_EXTRA_FLAGS "-dcl:high")
SET(CPACK_WIX_PRODUCT_ICON "D:/blenderDev/blender/release/windows/icons/winblender.ico")
SET(CPACK_WIX_SIZEOF_VOID_P "8")
SET(CPACK_WIX_TEMPLATE "D:/blenderDev/blender/../lib/win64_vc12/package/installer_wix/WIX.template")
SET(CPACK_WIX_UI_BANNER "D:/blenderDev/blender/../lib/win64_vc12/package/installer_wix/WIX_UI_BANNER.bmp")
SET(CPACK_WIX_UI_DIALOG "D:/blenderDev/blender/../lib/win64_vc12/package/installer_wix/WIX_UI_DIALOG.bmp")
SET(CPACK_WIX_UPGRADE_GUID "B767E4FD-7DE7-4094-B051-3AE62E13A17A")
