# CMake generated Testfile for 
# Source directory: D:/blenderDev/blender/source/blender/editors
# Build directory: D:/blenderDev/product/source/blender/editors
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
SUBDIRS(animation)
SUBDIRS(armature)
SUBDIRS(curve)
SUBDIRS(gpencil)
SUBDIRS(interface)
SUBDIRS(io)
SUBDIRS(mask)
SUBDIRS(mesh)
SUBDIRS(metaball)
SUBDIRS(object)
SUBDIRS(physics)
SUBDIRS(render)
SUBDIRS(screen)
SUBDIRS(sculpt_paint)
SUBDIRS(sound)
SUBDIRS(space_action)
SUBDIRS(space_api)
SUBDIRS(space_buttons)
SUBDIRS(space_clip)
SUBDIRS(space_console)
SUBDIRS(space_file)
SUBDIRS(space_graph)
SUBDIRS(space_image)
SUBDIRS(space_info)
SUBDIRS(space_logic)
SUBDIRS(space_nla)
SUBDIRS(space_node)
SUBDIRS(space_outliner)
SUBDIRS(space_script)
SUBDIRS(space_sequencer)
SUBDIRS(space_text)
SUBDIRS(space_time)
SUBDIRS(space_userpref)
SUBDIRS(space_view3d)
SUBDIRS(transform)
SUBDIRS(util)
SUBDIRS(uvedit)
SUBDIRS(datafiles)
